# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

FROM us-docker.pkg.dev/cros-registry/base-images/ubuntu:ubuntuProd_baseADB

# TODO(cdelagarza): Find out if the partner_testing_rsa
# is an abandoned path or not.
# RUN mkdir -p ~/.ssh
# COPY ssh/ ~/.ssh/
# RUN chmod 400 /~/.ssh/partner_testing_rsa || :

COPY cros-dut /usr/bin/
