// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.26.1
// source: infra/fleetconsole/api/fleetconsolerpc/service.proto

package fleetconsolerpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetConsole_Ping_FullMethodName = "/fleetconsole.FleetConsole/Ping"
)

// FleetConsoleClient is the client API for FleetConsole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetConsoleClient interface {
	// Ping does not send or receive any information. It just checks that the service is there.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type fleetConsoleClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetConsoleClient(cc grpc.ClientConnInterface) FleetConsoleClient {
	return &fleetConsoleClient{cc}
}

func (c *fleetConsoleClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, FleetConsole_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetConsoleServer is the server API for FleetConsole service.
// All implementations must embed UnimplementedFleetConsoleServer
// for forward compatibility.
type FleetConsoleServer interface {
	// Ping does not send or receive any information. It just checks that the service is there.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedFleetConsoleServer()
}

// UnimplementedFleetConsoleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFleetConsoleServer struct{}

func (UnimplementedFleetConsoleServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFleetConsoleServer) mustEmbedUnimplementedFleetConsoleServer() {}
func (UnimplementedFleetConsoleServer) testEmbeddedByValue()                      {}

// UnsafeFleetConsoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FleetConsoleServer will
// result in compilation errors.
type UnsafeFleetConsoleServer interface {
	mustEmbedUnimplementedFleetConsoleServer()
}

func RegisterFleetConsoleServer(s grpc.ServiceRegistrar, srv FleetConsoleServer) {
	// If the following call pancis, it indicates UnimplementedFleetConsoleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FleetConsole_ServiceDesc, srv)
}

func _FleetConsole_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetConsoleServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetConsole_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetConsoleServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetConsole_ServiceDesc is the grpc.ServiceDesc for FleetConsole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FleetConsole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleetconsole.FleetConsole",
	HandlerType: (*FleetConsoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _FleetConsole_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infra/fleetconsole/api/fleetconsolerpc/service.proto",
}
