// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: infra/fleetconsole/api/fleetconsolerpc/service.proto

package fleetconsolerpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceType int32

const (
	DeviceType_DEVICE_TYPE_UNSPECIFIED DeviceType = 0
	DeviceType_DEVICE_TYPE_VIRTUAL     DeviceType = 1
	DeviceType_DEVICE_TYPE_PHYSICAL    DeviceType = 2
)

// Enum value maps for DeviceType.
var (
	DeviceType_name = map[int32]string{
		0: "DEVICE_TYPE_UNSPECIFIED",
		1: "DEVICE_TYPE_VIRTUAL",
		2: "DEVICE_TYPE_PHYSICAL",
	}
	DeviceType_value = map[string]int32{
		"DEVICE_TYPE_UNSPECIFIED": 0,
		"DEVICE_TYPE_VIRTUAL":     1,
		"DEVICE_TYPE_PHYSICAL":    2,
	}
)

func (x DeviceType) Enum() *DeviceType {
	p := new(DeviceType)
	*p = x
	return p
}

func (x DeviceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceType) Descriptor() protoreflect.EnumDescriptor {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_enumTypes[0].Descriptor()
}

func (DeviceType) Type() protoreflect.EnumType {
	return &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_enumTypes[0]
}

func (x DeviceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceType.Descriptor instead.
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{0}
}

type DeviceState int32

const (
	DeviceState_DEVICE_STATE_UNSPECIFIED DeviceState = 0
	// Default state.
	// Device is available to be leased.
	DeviceState_DEVICE_STATE_AVAILABLE DeviceState = 1
	// Device is leased.
	DeviceState_DEVICE_STATE_LEASED DeviceState = 2
)

// Enum value maps for DeviceState.
var (
	DeviceState_name = map[int32]string{
		0: "DEVICE_STATE_UNSPECIFIED",
		1: "DEVICE_STATE_AVAILABLE",
		2: "DEVICE_STATE_LEASED",
	}
	DeviceState_value = map[string]int32{
		"DEVICE_STATE_UNSPECIFIED": 0,
		"DEVICE_STATE_AVAILABLE":   1,
		"DEVICE_STATE_LEASED":      2,
	}
)

func (x DeviceState) Enum() *DeviceState {
	p := new(DeviceState)
	*p = x
	return p
}

func (x DeviceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceState) Descriptor() protoreflect.EnumDescriptor {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_enumTypes[1].Descriptor()
}

func (DeviceState) Type() protoreflect.EnumType {
	return &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_enumTypes[1]
}

func (x DeviceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeviceState.Descriptor instead.
func (DeviceState) EnumDescriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{1}
}

// PingRequest intentionally contains nothing.
type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{0}
}

// PingResponse intentionally contains nothing.
type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{1}
}

// PingDeviceManagerRequest intentionally contains nothing.
type PingDeviceManagerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingDeviceManagerRequest) Reset() {
	*x = PingDeviceManagerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingDeviceManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDeviceManagerRequest) ProtoMessage() {}

func (x *PingDeviceManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDeviceManagerRequest.ProtoReflect.Descriptor instead.
func (*PingDeviceManagerRequest) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{2}
}

// PingDeviceManagerResponse intentionally contains nothing.
type PingDeviceManagerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingDeviceManagerResponse) Reset() {
	*x = PingDeviceManagerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingDeviceManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDeviceManagerResponse) ProtoMessage() {}

func (x *PingDeviceManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDeviceManagerResponse.ProtoReflect.Descriptor instead.
func (*PingDeviceManagerResponse) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{3}
}

type Device struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// In the case of VMs, device id could be the GCE instance name. For physical
	// DUTs we use the IDs we get from UFS.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// dut_id is the asset tag for a Device
	DutId   string         `protobuf:"bytes,6,opt,name=dut_id,json=dutId,proto3" json:"dut_id,omitempty"`
	Address *DeviceAddress `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Type    DeviceType     `protobuf:"varint,3,opt,name=type,proto3,enum=fleetconsole.DeviceType" json:"type,omitempty"`
	State   DeviceState    `protobuf:"varint,4,opt,name=state,proto3,enum=fleetconsole.DeviceState" json:"state,omitempty"`
	// // This proto contains per-DUT hardware relevant information including labels.
	DeviceSpec *DeviceSpec `protobuf:"bytes,5,opt,name=device_spec,json=deviceSpec,proto3" json:"device_spec,omitempty"`
}

func (x *Device) Reset() {
	*x = Device{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetDutId() string {
	if x != nil {
		return x.DutId
	}
	return ""
}

func (x *Device) GetAddress() *DeviceAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Device) GetType() DeviceType {
	if x != nil {
		return x.Type
	}
	return DeviceType_DEVICE_TYPE_UNSPECIFIED
}

func (x *Device) GetState() DeviceState {
	if x != nil {
		return x.State
	}
	return DeviceState_DEVICE_STATE_UNSPECIFIED
}

func (x *Device) GetDeviceSpec() *DeviceSpec {
	if x != nil {
		return x.DeviceSpec
	}
	return nil
}

type DeviceAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// IP address of the device.
	// For physical DUTs it can be a hostname.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *DeviceAddress) Reset() {
	*x = DeviceAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceAddress) ProtoMessage() {}

func (x *DeviceAddress) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceAddress.ProtoReflect.Descriptor instead.
func (*DeviceAddress) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceAddress) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DeviceAddress) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The maximum number of devices to return. The service may return fewer than
	// this value. If unspecified, at most 50 devices will be returned.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// A page token, received from a previous `ListDevices` call. Provide this to
	// retrieve the subsequent page. Returns first page if omitted.
	//
	// When paginating, all other parameters provided to `ListDevices` must match
	// the call that provided the page token.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	OrderBy   string `protobuf:"bytes,3,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListDevicesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListDevicesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListDevicesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of devices to be returned.
	Devices []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	// A token, which can be sent as `page_token` to retrieve the next page. If
	// this field is omitted, there are no subsequent pages.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListDevicesResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *ListDevicesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type DeviceSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A map for labels used to request a matching device.
	Labels map[string]*DeviceSpec_LabelValues `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DeviceSpec) Reset() {
	*x = DeviceSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSpec) ProtoMessage() {}

func (x *DeviceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSpec.ProtoReflect.Descriptor instead.
func (*DeviceSpec) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeviceSpec) GetLabels() map[string]*DeviceSpec_LabelValues {
	if x != nil {
		return x.Labels
	}
	return nil
}

type DeviceSpec_LabelValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *DeviceSpec_LabelValues) Reset() {
	*x = DeviceSpec_LabelValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeviceSpec_LabelValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSpec_LabelValues) ProtoMessage() {}

func (x *DeviceSpec_LabelValues) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSpec_LabelValues.ProtoReflect.Descriptor instead.
func (*DeviceSpec_LabelValues) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{8, 0}
}

func (x *DeviceSpec_LabelValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_infra_fleetconsole_api_fleetconsolerpc_service_proto protoreflect.FileDescriptor

var file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDesc = []byte{
	0x0a, 0x34, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1b, 0x0a, 0x19, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x80, 0x02, 0x0a,
	0x06, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x64, 0x75, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64, 0x75, 0x74, 0x49, 0x64, 0x12, 0x35,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2c, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x2f, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x73,
	0x70, 0x65, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x22,
	0x37, 0x0a, 0x0d, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x6b, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x42, 0x79, 0x22, 0x6d, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x07, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0f,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x22, 0xd2, 0x01, 0x0a, 0x0a, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x12, 0x3c, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f,
	0x6c, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x70, 0x65, 0x63, 0x2e, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x1a, 0x25, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x1a, 0x5f, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x3a, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x53, 0x70,
	0x65, 0x63, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x5c, 0x0a, 0x0a, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x44, 0x45, 0x56, 0x49, 0x43,
	0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x56, 0x49, 0x52, 0x54, 0x55, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x18, 0x0a,
	0x14, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x50, 0x48, 0x59,
	0x53, 0x49, 0x43, 0x41, 0x4c, 0x10, 0x02, 0x2a, 0x60, 0x0a, 0x0b, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53,
	0x54, 0x41, 0x54, 0x45, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x17, 0x0a, 0x13, 0x44, 0x45, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x4c, 0x45, 0x41, 0x53, 0x45, 0x44, 0x10, 0x02, 0x32, 0x89, 0x02, 0x0a, 0x0c, 0x46, 0x6c,
	0x65, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x50, 0x69,
	0x6e, 0x67, 0x12, 0x19, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x50, 0x69, 0x6e,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x11, 0x50, 0x69, 0x6e,
	0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x26,
	0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x54, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x20,
	0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x21, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x38, 0x5a, 0x36, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x72, 0x70, 0x63, 0x3b,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescOnce sync.Once
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescData = file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDesc
)

func file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP() []byte {
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescOnce.Do(func() {
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescData)
	})
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescData
}

var file_infra_fleetconsole_api_fleetconsolerpc_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_infra_fleetconsole_api_fleetconsolerpc_service_proto_goTypes = []interface{}{
	(DeviceType)(0),                   // 0: fleetconsole.DeviceType
	(DeviceState)(0),                  // 1: fleetconsole.DeviceState
	(*PingRequest)(nil),               // 2: fleetconsole.PingRequest
	(*PingResponse)(nil),              // 3: fleetconsole.PingResponse
	(*PingDeviceManagerRequest)(nil),  // 4: fleetconsole.PingDeviceManagerRequest
	(*PingDeviceManagerResponse)(nil), // 5: fleetconsole.PingDeviceManagerResponse
	(*Device)(nil),                    // 6: fleetconsole.Device
	(*DeviceAddress)(nil),             // 7: fleetconsole.DeviceAddress
	(*ListDevicesRequest)(nil),        // 8: fleetconsole.ListDevicesRequest
	(*ListDevicesResponse)(nil),       // 9: fleetconsole.ListDevicesResponse
	(*DeviceSpec)(nil),                // 10: fleetconsole.DeviceSpec
	(*DeviceSpec_LabelValues)(nil),    // 11: fleetconsole.DeviceSpec.LabelValues
	nil,                               // 12: fleetconsole.DeviceSpec.LabelsEntry
}
var file_infra_fleetconsole_api_fleetconsolerpc_service_proto_depIdxs = []int32{
	7,  // 0: fleetconsole.Device.address:type_name -> fleetconsole.DeviceAddress
	0,  // 1: fleetconsole.Device.type:type_name -> fleetconsole.DeviceType
	1,  // 2: fleetconsole.Device.state:type_name -> fleetconsole.DeviceState
	10, // 3: fleetconsole.Device.device_spec:type_name -> fleetconsole.DeviceSpec
	6,  // 4: fleetconsole.ListDevicesResponse.devices:type_name -> fleetconsole.Device
	12, // 5: fleetconsole.DeviceSpec.labels:type_name -> fleetconsole.DeviceSpec.LabelsEntry
	11, // 6: fleetconsole.DeviceSpec.LabelsEntry.value:type_name -> fleetconsole.DeviceSpec.LabelValues
	2,  // 7: fleetconsole.FleetConsole.Ping:input_type -> fleetconsole.PingRequest
	4,  // 8: fleetconsole.FleetConsole.PingDeviceManager:input_type -> fleetconsole.PingDeviceManagerRequest
	8,  // 9: fleetconsole.FleetConsole.ListDevices:input_type -> fleetconsole.ListDevicesRequest
	3,  // 10: fleetconsole.FleetConsole.Ping:output_type -> fleetconsole.PingResponse
	5,  // 11: fleetconsole.FleetConsole.PingDeviceManager:output_type -> fleetconsole.PingDeviceManagerResponse
	9,  // 12: fleetconsole.FleetConsole.ListDevices:output_type -> fleetconsole.ListDevicesResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_infra_fleetconsole_api_fleetconsolerpc_service_proto_init() }
func file_infra_fleetconsole_api_fleetconsolerpc_service_proto_init() {
	if File_infra_fleetconsole_api_fleetconsolerpc_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingDeviceManagerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingDeviceManagerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Device); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDevicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListDevicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeviceSpec_LabelValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infra_fleetconsole_api_fleetconsolerpc_service_proto_goTypes,
		DependencyIndexes: file_infra_fleetconsole_api_fleetconsolerpc_service_proto_depIdxs,
		EnumInfos:         file_infra_fleetconsole_api_fleetconsolerpc_service_proto_enumTypes,
		MessageInfos:      file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes,
	}.Build()
	File_infra_fleetconsole_api_fleetconsolerpc_service_proto = out.File
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDesc = nil
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_goTypes = nil
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_depIdxs = nil
}
