// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.26.1
// source: infra/fleetconsole/api/fleetconsolerpc/service.proto

package fleetconsolerpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingRequest intentionally contains nothing.
type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{0}
}

// PingResponse intentionally contains nothing.
type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{1}
}

// PingDeviceManagerRequest intentionally contains nothing.
type PingDeviceManagerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingDeviceManagerRequest) Reset() {
	*x = PingDeviceManagerRequest{}
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDeviceManagerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDeviceManagerRequest) ProtoMessage() {}

func (x *PingDeviceManagerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDeviceManagerRequest.ProtoReflect.Descriptor instead.
func (*PingDeviceManagerRequest) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{2}
}

// PingDeviceManagerResponse intentionally contains nothing.
type PingDeviceManagerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingDeviceManagerResponse) Reset() {
	*x = PingDeviceManagerResponse{}
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingDeviceManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingDeviceManagerResponse) ProtoMessage() {}

func (x *PingDeviceManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingDeviceManagerResponse.ProtoReflect.Descriptor instead.
func (*PingDeviceManagerResponse) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP(), []int{3}
}

var File_infra_fleetconsole_api_fleetconsolerpc_service_proto protoreflect.FileDescriptor

var file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDesc = []byte{
	0x0a, 0x34, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f,
	0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x22, 0x0d, 0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a, 0x18, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1b, 0x0a, 0x19, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xb3, 0x01, 0x0a,
	0x0c, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x12, 0x3d, 0x0a,
	0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x64, 0x0a, 0x11,
	0x50, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x12, 0x26, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x38, 0x5a, 0x36, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x72, 0x70, 0x63, 0x3b, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescOnce sync.Once
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescData = file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDesc
)

func file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescGZIP() []byte {
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescOnce.Do(func() {
		file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescData)
	})
	return file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDescData
}

var file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_infra_fleetconsole_api_fleetconsolerpc_service_proto_goTypes = []any{
	(*PingRequest)(nil),               // 0: fleetconsole.PingRequest
	(*PingResponse)(nil),              // 1: fleetconsole.PingResponse
	(*PingDeviceManagerRequest)(nil),  // 2: fleetconsole.PingDeviceManagerRequest
	(*PingDeviceManagerResponse)(nil), // 3: fleetconsole.PingDeviceManagerResponse
}
var file_infra_fleetconsole_api_fleetconsolerpc_service_proto_depIdxs = []int32{
	0, // 0: fleetconsole.FleetConsole.Ping:input_type -> fleetconsole.PingRequest
	2, // 1: fleetconsole.FleetConsole.PingDeviceManager:input_type -> fleetconsole.PingDeviceManagerRequest
	1, // 2: fleetconsole.FleetConsole.Ping:output_type -> fleetconsole.PingResponse
	3, // 3: fleetconsole.FleetConsole.PingDeviceManager:output_type -> fleetconsole.PingDeviceManagerResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infra_fleetconsole_api_fleetconsolerpc_service_proto_init() }
func file_infra_fleetconsole_api_fleetconsolerpc_service_proto_init() {
	if File_infra_fleetconsole_api_fleetconsolerpc_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infra_fleetconsole_api_fleetconsolerpc_service_proto_goTypes,
		DependencyIndexes: file_infra_fleetconsole_api_fleetconsolerpc_service_proto_depIdxs,
		MessageInfos:      file_infra_fleetconsole_api_fleetconsolerpc_service_proto_msgTypes,
	}.Build()
	File_infra_fleetconsole_api_fleetconsolerpc_service_proto = out.File
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_rawDesc = nil
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_goTypes = nil
	file_infra_fleetconsole_api_fleetconsolerpc_service_proto_depIdxs = nil
}
