// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: infra/libs/fleet/scheduling/api/task_scheduling.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProviderId is the ID of various tasking scheduling providers.
type ProviderId int32

const (
	ProviderId_PROVIDER_ID_UNSPECIFIED ProviderId = 0
	ProviderId_PROVIDER_ID_SCHEDUKE    ProviderId = 1
)

// Enum value maps for ProviderId.
var (
	ProviderId_name = map[int32]string{
		0: "PROVIDER_ID_UNSPECIFIED",
		1: "PROVIDER_ID_SCHEDUKE",
	}
	ProviderId_value = map[string]int32{
		"PROVIDER_ID_UNSPECIFIED": 0,
		"PROVIDER_ID_SCHEDUKE":    1,
	}
)

func (x ProviderId) Enum() *ProviderId {
	p := new(ProviderId)
	*p = x
	return p
}

func (x ProviderId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProviderId) Descriptor() protoreflect.EnumDescriptor {
	return file_infra_libs_fleet_scheduling_api_task_scheduling_proto_enumTypes[0].Descriptor()
}

func (ProviderId) Type() protoreflect.EnumType {
	return &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_enumTypes[0]
}

func (x ProviderId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProviderId.Descriptor instead.
func (ProviderId) EnumDescriptor() ([]byte, []int) {
	return file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescGZIP(), []int{0}
}

// The Scheduke environment to connect to.
type Config_SchedukeBackend_Environment int32

const (
	Config_SchedukeBackend_ENV_UNSPECIFIED Config_SchedukeBackend_Environment = 0
	Config_SchedukeBackend_ENV_LOCAL       Config_SchedukeBackend_Environment = 1
	Config_SchedukeBackend_ENV_STAGING     Config_SchedukeBackend_Environment = 2
	Config_SchedukeBackend_ENV_PRODUCTION  Config_SchedukeBackend_Environment = 3
)

// Enum value maps for Config_SchedukeBackend_Environment.
var (
	Config_SchedukeBackend_Environment_name = map[int32]string{
		0: "ENV_UNSPECIFIED",
		1: "ENV_LOCAL",
		2: "ENV_STAGING",
		3: "ENV_PRODUCTION",
	}
	Config_SchedukeBackend_Environment_value = map[string]int32{
		"ENV_UNSPECIFIED": 0,
		"ENV_LOCAL":       1,
		"ENV_STAGING":     2,
		"ENV_PRODUCTION":  3,
	}
)

func (x Config_SchedukeBackend_Environment) Enum() *Config_SchedukeBackend_Environment {
	p := new(Config_SchedukeBackend_Environment)
	*p = x
	return p
}

func (x Config_SchedukeBackend_Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Config_SchedukeBackend_Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_infra_libs_fleet_scheduling_api_task_scheduling_proto_enumTypes[1].Descriptor()
}

func (Config_SchedukeBackend_Environment) Type() protoreflect.EnumType {
	return &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_enumTypes[1]
}

func (x Config_SchedukeBackend_Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Config_SchedukeBackend_Environment.Descriptor instead.
func (Config_SchedukeBackend_Environment) EnumDescriptor() ([]byte, []int) {
	return file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescGZIP(), []int{0, 0, 0}
}

// Config specifies which backend to call task scheduling and the parameters for
// establishing the backend.
type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Backend:
	//
	//	*Config_SchedukeBackend_
	Backend isConfig_Backend `protobuf_oneof:"backend"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescGZIP(), []int{0}
}

func (m *Config) GetBackend() isConfig_Backend {
	if m != nil {
		return m.Backend
	}
	return nil
}

func (x *Config) GetSchedukeBackend() *Config_SchedukeBackend {
	if x, ok := x.GetBackend().(*Config_SchedukeBackend_); ok {
		return x.SchedukeBackend
	}
	return nil
}

type isConfig_Backend interface {
	isConfig_Backend()
}

type Config_SchedukeBackend_ struct {
	SchedukeBackend *Config_SchedukeBackend `protobuf:"bytes,1,opt,name=scheduke_backend,json=schedukeBackend,proto3,oneof"`
}

func (*Config_SchedukeBackend_) isConfig_Backend() {}

// Task contains a task ID and url provided by the backend.
type Task struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Task) Reset() {
	*x = Task{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// ScheduleTaskRequest is the request for the TaskSchedulingAPI.ScheduleTask
// endpoint.
type ScheduleTaskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Configuration of the backend to start the instance.
	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *ScheduleTaskRequest) Reset() {
	*x = ScheduleTaskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScheduleTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleTaskRequest) ProtoMessage() {}

func (x *ScheduleTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleTaskRequest.ProtoReflect.Descriptor instead.
func (*ScheduleTaskRequest) Descriptor() ([]byte, []int) {
	return file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescGZIP(), []int{2}
}

func (x *ScheduleTaskRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// CancelTasksRequest is the request for the TaskSchedulingAPI.CancelTasks
// endpoint.
type CancelTasksRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Configuration of the backend to start the instance.
	Config  *Config  `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	TaskIds []string `protobuf:"bytes,2,rep,name=task_ids,json=taskIds,proto3" json:"task_ids,omitempty"`
}

func (x *CancelTasksRequest) Reset() {
	*x = CancelTasksRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTasksRequest) ProtoMessage() {}

func (x *CancelTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTasksRequest.ProtoReflect.Descriptor instead.
func (*CancelTasksRequest) Descriptor() ([]byte, []int) {
	return file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescGZIP(), []int{3}
}

func (x *CancelTasksRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CancelTasksRequest) GetTaskIds() []string {
	if x != nil {
		return x.TaskIds
	}
	return nil
}

// SchedukeBackend contains Scheduke params. The fields will be passed to
// Scheduke service for task scheduling. Required fields must be passed.
type Config_SchedukeBackend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Env  Config_SchedukeBackend_Environment `protobuf:"varint,1,opt,name=env,proto3,enum=scheduling.api.Config_SchedukeBackend_Environment" json:"env,omitempty"`
	Pool string                             `protobuf:"bytes,2,opt,name=pool,proto3" json:"pool,omitempty"`
}

func (x *Config_SchedukeBackend) Reset() {
	*x = Config_SchedukeBackend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config_SchedukeBackend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config_SchedukeBackend) ProtoMessage() {}

func (x *Config_SchedukeBackend) ProtoReflect() protoreflect.Message {
	mi := &file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config_SchedukeBackend.ProtoReflect.Descriptor instead.
func (*Config_SchedukeBackend) Descriptor() ([]byte, []int) {
	return file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Config_SchedukeBackend) GetEnv() Config_SchedukeBackend_Environment {
	if x != nil {
		return x.Env
	}
	return Config_SchedukeBackend_ENV_UNSPECIFIED
}

func (x *Config_SchedukeBackend) GetPool() string {
	if x != nil {
		return x.Pool
	}
	return ""
}

var File_infra_libs_fleet_scheduling_api_task_scheduling_proto protoreflect.FileDescriptor

var file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDesc = []byte{
	0x0a, 0x35, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c,
	0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x22, 0xae, 0x02, 0x0a, 0x06, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x12, 0x53, 0x0a, 0x10, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6b, 0x65, 0x5f, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6b, 0x65, 0x42, 0x61, 0x63,
	0x6b, 0x65, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6b, 0x65,
	0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x1a, 0xc3, 0x01, 0x0a, 0x0f, 0x53, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6b, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x12, 0x44, 0x0a, 0x03, 0x65,
	0x6e, 0x76, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x32, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64,
	0x75, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67,
	0x2e, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6b, 0x65, 0x42, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2e, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x03, 0x65, 0x6e,
	0x76, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x70, 0x6f, 0x6f, 0x6c, 0x22, 0x56, 0x0a, 0x0b, 0x45, 0x6e, 0x76, 0x69, 0x72, 0x6f, 0x6e,
	0x6d, 0x65, 0x6e, 0x74, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x4e, 0x56, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x4e, 0x56,
	0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x45, 0x4e, 0x56, 0x5f,
	0x53, 0x54, 0x41, 0x47, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x4e, 0x56,
	0x5f, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x03, 0x42, 0x09, 0x0a,
	0x07, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x22, 0x28, 0x0a, 0x04, 0x54, 0x61, 0x73, 0x6b,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x22, 0x45, 0x0a, 0x13, 0x53, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x54, 0x61,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x63, 0x68, 0x65,
	0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x22, 0x5f, 0x0a, 0x12, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x2e, 0x0a, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x19, 0x0a, 0x08, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x74, 0x61, 0x73, 0x6b, 0x49, 0x64, 0x73, 0x2a, 0x43, 0x0a, 0x0a, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x17, 0x50, 0x52, 0x4f, 0x56,
	0x49, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46,
	0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x44, 0x45,
	0x52, 0x5f, 0x49, 0x44, 0x5f, 0x53, 0x43, 0x48, 0x45, 0x44, 0x55, 0x4b, 0x45, 0x10, 0x01, 0x42,
	0x21, 0x5a, 0x1f, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x6c, 0x69, 0x62, 0x73, 0x2f, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x2f, 0x73, 0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x69, 0x6e, 0x67, 0x2f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescOnce sync.Once
	file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescData = file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDesc
)

func file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescGZIP() []byte {
	file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescOnce.Do(func() {
		file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescData = protoimpl.X.CompressGZIP(file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescData)
	})
	return file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDescData
}

var file_infra_libs_fleet_scheduling_api_task_scheduling_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_infra_libs_fleet_scheduling_api_task_scheduling_proto_goTypes = []interface{}{
	(ProviderId)(0),                         // 0: scheduling.api.ProviderId
	(Config_SchedukeBackend_Environment)(0), // 1: scheduling.api.Config.SchedukeBackend.Environment
	(*Config)(nil),                          // 2: scheduling.api.Config
	(*Task)(nil),                            // 3: scheduling.api.Task
	(*ScheduleTaskRequest)(nil),             // 4: scheduling.api.ScheduleTaskRequest
	(*CancelTasksRequest)(nil),              // 5: scheduling.api.CancelTasksRequest
	(*Config_SchedukeBackend)(nil),          // 6: scheduling.api.Config.SchedukeBackend
}
var file_infra_libs_fleet_scheduling_api_task_scheduling_proto_depIdxs = []int32{
	6, // 0: scheduling.api.Config.scheduke_backend:type_name -> scheduling.api.Config.SchedukeBackend
	2, // 1: scheduling.api.ScheduleTaskRequest.config:type_name -> scheduling.api.Config
	2, // 2: scheduling.api.CancelTasksRequest.config:type_name -> scheduling.api.Config
	1, // 3: scheduling.api.Config.SchedukeBackend.env:type_name -> scheduling.api.Config.SchedukeBackend.Environment
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_infra_libs_fleet_scheduling_api_task_scheduling_proto_init() }
func file_infra_libs_fleet_scheduling_api_task_scheduling_proto_init() {
	if File_infra_libs_fleet_scheduling_api_task_scheduling_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Task); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScheduleTaskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelTasksRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config_SchedukeBackend); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Config_SchedukeBackend_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infra_libs_fleet_scheduling_api_task_scheduling_proto_goTypes,
		DependencyIndexes: file_infra_libs_fleet_scheduling_api_task_scheduling_proto_depIdxs,
		EnumInfos:         file_infra_libs_fleet_scheduling_api_task_scheduling_proto_enumTypes,
		MessageInfos:      file_infra_libs_fleet_scheduling_api_task_scheduling_proto_msgTypes,
	}.Build()
	File_infra_libs_fleet_scheduling_api_task_scheduling_proto = out.File
	file_infra_libs_fleet_scheduling_api_task_scheduling_proto_rawDesc = nil
	file_infra_libs_fleet_scheduling_api_task_scheduling_proto_goTypes = nil
	file_infra_libs_fleet_scheduling_api_task_scheduling_proto_depIdxs = nil
}
