// Copyright 2023 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: infra/cros/fleetcost/api/rpc/service.proto

package fleetcostpb

import prpc "go.chromium.org/luci/grpc/prpc"

import (
	context "context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	models "infra/cros/fleetcost/api/models"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingRequest intentionally contains nothing.
type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{0}
}

// PingResponse intentionally contains nothing.
type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{1}
}

// PingUFSRequest intentionally contains nothing.
type PingUFSRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingUFSRequest) Reset() {
	*x = PingUFSRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingUFSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingUFSRequest) ProtoMessage() {}

func (x *PingUFSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingUFSRequest.ProtoReflect.Descriptor instead.
func (*PingUFSRequest) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{2}
}

// PingUFSResponse contains information about the request sent to and returned from UFS.
//
// This RPC is intended solely for diagnostic purposes.
type PingUFSResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ufs_request is the request to UFS, encoded as JSON.
	UfsRequest *anypb.Any `protobuf:"bytes,1,opt,name=ufs_request,json=ufsRequest,proto3" json:"ufs_request,omitempty"`
	// ufs_response is the response from UFS, encoded as JSON.
	UfsResponse *anypb.Any `protobuf:"bytes,2,opt,name=ufs_response,json=ufsResponse,proto3" json:"ufs_response,omitempty"`
	// ufs_error is the error we encountered from trying to ping UFS.
	UfsError string `protobuf:"bytes,3,opt,name=ufs_error,json=ufsError,proto3" json:"ufs_error,omitempty"`
	// ufs_hostname is the hostname of the UFS instance that we contacted.
	UfsHostname string `protobuf:"bytes,4,opt,name=ufs_hostname,json=ufsHostname,proto3" json:"ufs_hostname,omitempty"`
}

func (x *PingUFSResponse) Reset() {
	*x = PingUFSResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingUFSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingUFSResponse) ProtoMessage() {}

func (x *PingUFSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingUFSResponse.ProtoReflect.Descriptor instead.
func (*PingUFSResponse) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{3}
}

func (x *PingUFSResponse) GetUfsRequest() *anypb.Any {
	if x != nil {
		return x.UfsRequest
	}
	return nil
}

func (x *PingUFSResponse) GetUfsResponse() *anypb.Any {
	if x != nil {
		return x.UfsResponse
	}
	return nil
}

func (x *PingUFSResponse) GetUfsError() string {
	if x != nil {
		return x.UfsError
	}
	return ""
}

func (x *PingUFSResponse) GetUfsHostname() string {
	if x != nil {
		return x.UfsHostname
	}
	return ""
}

// CreateCostIndicatorRequest creates a new cost indicator.
type CreateCostIndicatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostIndicator *models.CostIndicator `protobuf:"bytes,1,opt,name=cost_indicator,json=costIndicator,proto3" json:"cost_indicator,omitempty"`
}

func (x *CreateCostIndicatorRequest) Reset() {
	*x = CreateCostIndicatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCostIndicatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCostIndicatorRequest) ProtoMessage() {}

func (x *CreateCostIndicatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCostIndicatorRequest.ProtoReflect.Descriptor instead.
func (*CreateCostIndicatorRequest) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCostIndicatorRequest) GetCostIndicator() *models.CostIndicator {
	if x != nil {
		return x.CostIndicator
	}
	return nil
}

// CreateCostIndicatorResponse contains the newly created CostIndicator.
type CreateCostIndicatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostIndicator *models.CostIndicator `protobuf:"bytes,1,opt,name=cost_indicator,json=costIndicator,proto3" json:"cost_indicator,omitempty"`
}

func (x *CreateCostIndicatorResponse) Reset() {
	*x = CreateCostIndicatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateCostIndicatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCostIndicatorResponse) ProtoMessage() {}

func (x *CreateCostIndicatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCostIndicatorResponse.ProtoReflect.Descriptor instead.
func (*CreateCostIndicatorResponse) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCostIndicatorResponse) GetCostIndicator() *models.CostIndicator {
	if x != nil {
		return x.CostIndicator
	}
	return nil
}

// ListCostIndicatorsRequest lists the cost indicators.
type ListCostIndicatorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageSize int32 `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	// TODO(gregorynisbet): Do we need filter disjunctions here? For the moment, don't add them.
	Filter *ListCostIndicatorsFilter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
}

func (x *ListCostIndicatorsRequest) Reset() {
	*x = ListCostIndicatorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCostIndicatorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCostIndicatorsRequest) ProtoMessage() {}

func (x *ListCostIndicatorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCostIndicatorsRequest.ProtoReflect.Descriptor instead.
func (*ListCostIndicatorsRequest) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListCostIndicatorsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCostIndicatorsRequest) GetFilter() *ListCostIndicatorsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// ListCostIndicatorsFilter is a filter query containing all the fields that can be filtered on.
//
// TODO(gregorynisbet): Do we want a separate Boolean field for searching for empty boards, models, SKUs?
//
//	Does the datastore query engine support this well?
type ListCostIndicatorsFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Board is the board of the cost indicator in question.
	Board string `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	// Model is the model of the cost indicator in question
	Model string `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	// Sku is the SKU of the cost indicator in question.
	Sku string `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	// Location is the location as a string.
	Location string `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	// Type is the type as a string.
	Type string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *ListCostIndicatorsFilter) Reset() {
	*x = ListCostIndicatorsFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCostIndicatorsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCostIndicatorsFilter) ProtoMessage() {}

func (x *ListCostIndicatorsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCostIndicatorsFilter.ProtoReflect.Descriptor instead.
func (*ListCostIndicatorsFilter) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListCostIndicatorsFilter) GetBoard() string {
	if x != nil {
		return x.Board
	}
	return ""
}

func (x *ListCostIndicatorsFilter) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ListCostIndicatorsFilter) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *ListCostIndicatorsFilter) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListCostIndicatorsFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// ListCostIndicatorsResponse lists cost indicators
type ListCostIndicatorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostIndicator []*models.CostIndicator `protobuf:"bytes,1,rep,name=cost_indicator,json=costIndicator,proto3" json:"cost_indicator,omitempty"`
}

func (x *ListCostIndicatorsResponse) Reset() {
	*x = ListCostIndicatorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCostIndicatorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCostIndicatorsResponse) ProtoMessage() {}

func (x *ListCostIndicatorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCostIndicatorsResponse.ProtoReflect.Descriptor instead.
func (*ListCostIndicatorsResponse) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListCostIndicatorsResponse) GetCostIndicator() []*models.CostIndicator {
	if x != nil {
		return x.CostIndicator
	}
	return nil
}

// UpdateCostIndicatorRequest updates a cost indicator.
type UpdateCostIndicatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostIndicator *models.CostIndicator `protobuf:"bytes,1,opt,name=cost_indicator,json=costIndicator,proto3" json:"cost_indicator,omitempty"`
	// The list of fields to be updated.
	UpdateMask *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
}

func (x *UpdateCostIndicatorRequest) Reset() {
	*x = UpdateCostIndicatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCostIndicatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCostIndicatorRequest) ProtoMessage() {}

func (x *UpdateCostIndicatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCostIndicatorRequest.ProtoReflect.Descriptor instead.
func (*UpdateCostIndicatorRequest) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCostIndicatorRequest) GetCostIndicator() *models.CostIndicator {
	if x != nil {
		return x.CostIndicator
	}
	return nil
}

func (x *UpdateCostIndicatorRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateCostIndicatorResponse contains a CostIndicator.
type UpdateCostIndicatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostIndicator *models.CostIndicator `protobuf:"bytes,1,opt,name=cost_indicator,json=costIndicator,proto3" json:"cost_indicator,omitempty"`
}

func (x *UpdateCostIndicatorResponse) Reset() {
	*x = UpdateCostIndicatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateCostIndicatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCostIndicatorResponse) ProtoMessage() {}

func (x *UpdateCostIndicatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCostIndicatorResponse.ProtoReflect.Descriptor instead.
func (*UpdateCostIndicatorResponse) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCostIndicatorResponse) GetCostIndicator() *models.CostIndicator {
	if x != nil {
		return x.CostIndicator
	}
	return nil
}

// GetCostResultRequest gets information about the cost of a device.
type GetCostResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeviceId    string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Hostname    string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ForceUpdate bool   `protobuf:"varint,3,opt,name=force_update,json=forceUpdate,proto3" json:"force_update,omitempty"`
	// forgive missing entries forgives entries that are missing.
	ForgiveMissingEntries bool `protobuf:"varint,4,opt,name=forgive_missing_entries,json=forgiveMissingEntries,proto3" json:"forgive_missing_entries,omitempty"`
}

func (x *GetCostResultRequest) Reset() {
	*x = GetCostResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCostResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCostResultRequest) ProtoMessage() {}

func (x *GetCostResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCostResultRequest.ProtoReflect.Descriptor instead.
func (*GetCostResultRequest) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetCostResultRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetCostResultRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *GetCostResultRequest) GetForceUpdate() bool {
	if x != nil {
		return x.ForceUpdate
	}
	return false
}

func (x *GetCostResultRequest) GetForgiveMissingEntries() bool {
	if x != nil {
		return x.ForgiveMissingEntries
	}
	return false
}

// GetCostResultResponse is the cost detail information obtained by GetCostResult.
type GetCostResultResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result *models.CostResult `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Report *models.CostReport `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
}

func (x *GetCostResultResponse) Reset() {
	*x = GetCostResultResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCostResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCostResultResponse) ProtoMessage() {}

func (x *GetCostResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCostResultResponse.ProtoReflect.Descriptor instead.
func (*GetCostResultResponse) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetCostResultResponse) GetResult() *models.CostResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetCostResultResponse) GetReport() *models.CostReport {
	if x != nil {
		return x.Report
	}
	return nil
}

// DeleteCostIndicatorRequest deletes a cost_indicator
type DeleteCostIndicatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostIndicator *models.CostIndicator `protobuf:"bytes,1,opt,name=cost_indicator,json=costIndicator,proto3" json:"cost_indicator,omitempty"`
}

func (x *DeleteCostIndicatorRequest) Reset() {
	*x = DeleteCostIndicatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCostIndicatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCostIndicatorRequest) ProtoMessage() {}

func (x *DeleteCostIndicatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCostIndicatorRequest.ProtoReflect.Descriptor instead.
func (*DeleteCostIndicatorRequest) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteCostIndicatorRequest) GetCostIndicator() *models.CostIndicator {
	if x != nil {
		return x.CostIndicator
	}
	return nil
}

// DeleteCostIndicatorResponse deletes a cost_indicator
type DeleteCostIndicatorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CostIndicator *models.CostIndicator `protobuf:"bytes,1,opt,name=cost_indicator,json=costIndicator,proto3" json:"cost_indicator,omitempty"`
}

func (x *DeleteCostIndicatorResponse) Reset() {
	*x = DeleteCostIndicatorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteCostIndicatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCostIndicatorResponse) ProtoMessage() {}

func (x *DeleteCostIndicatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCostIndicatorResponse.ProtoReflect.Descriptor instead.
func (*DeleteCostIndicatorResponse) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteCostIndicatorResponse) GetCostIndicator() *models.CostIndicator {
	if x != nil {
		return x.CostIndicator
	}
	return nil
}

// PersistToBigqueryRequest does not contain any info, since
// PersistToBigquery is intended to be called as a cron job.
type PersistToBigqueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// If readonly is true, then we perform a dry run and do not update BigQuery.
	// If readonly is false, then we do update BigQuery.
	Readonly bool `protobuf:"varint,1,opt,name=readonly,proto3" json:"readonly,omitempty"`
}

func (x *PersistToBigqueryRequest) Reset() {
	*x = PersistToBigqueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersistToBigqueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistToBigqueryRequest) ProtoMessage() {}

func (x *PersistToBigqueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistToBigqueryRequest.ProtoReflect.Descriptor instead.
func (*PersistToBigqueryRequest) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{15}
}

func (x *PersistToBigqueryRequest) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

type PersistToBigqueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Persisted records is the number of records that were persisted.
	PersistedRecords int32 `protobuf:"varint,1,opt,name=persisted_records,json=persistedRecords,proto3" json:"persisted_records,omitempty"`
	// Succeeded is true if and only if no errors at all were encountered during persistence.
	Succeeded bool `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
}

func (x *PersistToBigqueryResponse) Reset() {
	*x = PersistToBigqueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersistToBigqueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersistToBigqueryResponse) ProtoMessage() {}

func (x *PersistToBigqueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersistToBigqueryResponse.ProtoReflect.Descriptor instead.
func (*PersistToBigqueryResponse) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{16}
}

func (x *PersistToBigqueryResponse) GetPersistedRecords() int32 {
	if x != nil {
		return x.PersistedRecords
	}
	return 0
}

func (x *PersistToBigqueryResponse) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

// RepopulateCacheRequest doesn't contain any information. We always persist the entire cache.
type RepopulateCacheRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// forgive missing entries forgives entries that are missing.
	ForgiveMissingEntries bool `protobuf:"varint,1,opt,name=forgive_missing_entries,json=forgiveMissingEntries,proto3" json:"forgive_missing_entries,omitempty"`
}

func (x *RepopulateCacheRequest) Reset() {
	*x = RepopulateCacheRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepopulateCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepopulateCacheRequest) ProtoMessage() {}

func (x *RepopulateCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepopulateCacheRequest.ProtoReflect.Descriptor instead.
func (*RepopulateCacheRequest) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{17}
}

func (x *RepopulateCacheRequest) GetForgiveMissingEntries() bool {
	if x != nil {
		return x.ForgiveMissingEntries
	}
	return false
}

// RepopulateCacheResponse records the result of repopulating the cache.
type RepopulateCacheResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Persisted records is the number of records that were repopulated.
	ProcessedRecords int32 `protobuf:"varint,1,opt,name=processed_records,json=processedRecords,proto3" json:"processed_records,omitempty"`
	// Succeeded is true if and only if no errors at all were encountered when repopulating the cache.
	Succeeded bool `protobuf:"varint,2,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
}

func (x *RepopulateCacheResponse) Reset() {
	*x = RepopulateCacheResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepopulateCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepopulateCacheResponse) ProtoMessage() {}

func (x *RepopulateCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepopulateCacheResponse.ProtoReflect.Descriptor instead.
func (*RepopulateCacheResponse) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{18}
}

func (x *RepopulateCacheResponse) GetProcessedRecords() int32 {
	if x != nil {
		return x.ProcessedRecords
	}
	return 0
}

func (x *RepopulateCacheResponse) GetSucceeded() bool {
	if x != nil {
		return x.Succeeded
	}
	return false
}

// CreateVariableRequest creates a new variable.
type CreateVariableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Variable *models.Variable `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
}

func (x *CreateVariableRequest) Reset() {
	*x = CreateVariableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVariableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariableRequest) ProtoMessage() {}

func (x *CreateVariableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariableRequest.ProtoReflect.Descriptor instead.
func (*CreateVariableRequest) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{19}
}

func (x *CreateVariableRequest) GetVariable() *models.Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

// CreateVariableResponse contains only the newly created variable
type CreateVariableResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Variable *models.Variable `protobuf:"bytes,1,opt,name=variable,proto3" json:"variable,omitempty"`
}

func (x *CreateVariableResponse) Reset() {
	*x = CreateVariableResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVariableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariableResponse) ProtoMessage() {}

func (x *CreateVariableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariableResponse.ProtoReflect.Descriptor instead.
func (*CreateVariableResponse) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP(), []int{20}
}

func (x *CreateVariableResponse) GetVariable() *models.Variable {
	if x != nil {
		return x.Variable
	}
	return nil
}

var File_infra_cros_fleetcost_api_rpc_service_proto protoreflect.FileDescriptor

var file_infra_cros_fleetcost_api_rpc_service_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f,
	0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x61, 0x6e, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2f, 0x69, 0x6e, 0x66,
	0x72, 0x61, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x69, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2c, 0x69, 0x6e,
	0x66, 0x72, 0x61, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f,
	0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x31, 0x69, 0x6e, 0x66, 0x72,
	0x61, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x63, 0x6f, 0x73, 0x74,
	0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2e, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63,
	0x6f, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76,
	0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0d, 0x0a,
	0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x0a, 0x0e,
	0x50, 0x69, 0x6e, 0x67, 0x55, 0x46, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc1,
	0x01, 0x0a, 0x0f, 0x50, 0x69, 0x6e, 0x67, 0x55, 0x46, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x35, 0x0a, 0x0b, 0x75, 0x66, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0a, 0x75,
	0x66, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x37, 0x0a, 0x0c, 0x75, 0x66, 0x73,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x0b, 0x75, 0x66, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x66, 0x73, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x66, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x21, 0x0a, 0x0c, 0x75, 0x66, 0x73, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x66, 0x73, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x68, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x74,
	0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x4a, 0x0a, 0x0e, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0d, 0x63,
	0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x69, 0x0a, 0x1b,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0e, 0x63,
	0x6f, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x49,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x73, 0x74, 0x49, 0x6e,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x7c, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x43,
	0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x43, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2b, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x06, 0x66,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x88, 0x01, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x62, 0x6f, 0x61, 0x72, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x6b, 0x75, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x6b, 0x75,
	0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0x68, 0x0a, 0x1a, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a,
	0x0a, 0x0e, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f,
	0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f,
	0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x73,
	0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0xaa, 0x01, 0x0a, 0x1a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x0e, 0x63, 0x6f, 0x73,
	0x74, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x42, 0x03, 0xe0, 0x41, 0x02, 0x52, 0x0d, 0x63, 0x6f, 0x73,
	0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x61, 0x73, 0x6b, 0x22, 0x69, 0x0a, 0x1b, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0e, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x69,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x22, 0xaa, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x5f, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x66, 0x6f, 0x72, 0x63,
	0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x66, 0x6f, 0x72, 0x67, 0x69,
	0x76, 0x65, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x66, 0x6f, 0x72, 0x67, 0x69, 0x76,
	0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22,
	0x8b, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x38, 0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x68, 0x0a,
	0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63,
	0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4a, 0x0a, 0x0e, 0x63,
	0x6f, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x49,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x73, 0x74, 0x49, 0x6e,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x69, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x0e, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x69,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x0d, 0x63, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x22, 0x36, 0x0a, 0x18, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x42,
	0x69, 0x67, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x72, 0x65, 0x61, 0x64, 0x6f, 0x6e, 0x6c, 0x79, 0x22, 0x66, 0x0a, 0x19, 0x50, 0x65,
	0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x42, 0x69, 0x67, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x70, 0x65, 0x72, 0x73, 0x69,
	0x73, 0x74, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x10, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x64, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64,
	0x65, 0x64, 0x22, 0x50, 0x0a, 0x16, 0x52, 0x65, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x17,
	0x66, 0x6f, 0x72, 0x67, 0x69, 0x76, 0x65, 0x5f, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x5f,
	0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x66,
	0x6f, 0x72, 0x67, 0x69, 0x76, 0x65, 0x4d, 0x69, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x45, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x22, 0x64, 0x0a, 0x17, 0x52, 0x65, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x2b, 0x0a, 0x11, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x10, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x65, 0x64, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x73, 0x75, 0x63, 0x63, 0x65, 0x65, 0x64, 0x65, 0x64, 0x22, 0x53, 0x0a, 0x15, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x3a, 0x0a, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x22,
	0x54, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x76, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x76, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x32, 0xdf, 0x0a, 0x0a, 0x09, 0x46, 0x6c, 0x65, 0x65, 0x74, 0x43,
	0x6f, 0x73, 0x74, 0x12, 0x59, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x1e, 0x2e, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x66, 0x6c,
	0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x10, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x0a, 0x22, 0x08, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x66,
	0x0a, 0x07, 0x50, 0x69, 0x6e, 0x67, 0x55, 0x46, 0x53, 0x12, 0x21, 0x2e, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x69,
	0x6e, 0x67, 0x55, 0x46, 0x53, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x55, 0x46, 0x53, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x14, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0e, 0x22, 0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x69,
	0x6e, 0x67, 0x2d, 0x75, 0x66, 0x73, 0x12, 0x97, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2d,
	0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x19, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x2d, 0x63, 0x6f, 0x73, 0x74, 0x2d, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x93, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x2c, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63,
	0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f,
	0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x20, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1a, 0x22, 0x18, 0x2f, 0x76,
	0x31, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x2d, 0x63, 0x6f, 0x73, 0x74, 0x2d, 0x69, 0x6e, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x73, 0x12, 0x97, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2d,
	0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x19, 0x2f, 0x76, 0x31, 0x2f, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x2d, 0x63, 0x6f, 0x73, 0x74, 0x2d, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x97, 0x01, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x49,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x2d, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63,
	0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22,
	0x19, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x2d, 0x63, 0x6f, 0x73, 0x74,
	0x2d, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x82, 0x01, 0x0a, 0x0e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x28, 0x2e,
	0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63,
	0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x13, 0x2f, 0x76, 0x31, 0x2f,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x2d, 0x76, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12,
	0x7f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x27, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x22, 0x13, 0x2f, 0x76, 0x31,
	0x2f, 0x67, 0x65, 0x74, 0x2d, 0x63, 0x6f, 0x73, 0x74, 0x2d, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x95, 0x01, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x42, 0x69,
	0x67, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x2b, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f,
	0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x69,
	0x73, 0x74, 0x54, 0x6f, 0x42, 0x69, 0x67, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x54,
	0x6f, 0x42, 0x69, 0x67, 0x71, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x25, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1f, 0x22, 0x1d, 0x2f, 0x76, 0x31, 0x2f, 0x74,
	0x61, 0x73, 0x6b, 0x73, 0x2f, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x2d, 0x74, 0x6f, 0x2d,
	0x62, 0x69, 0x67, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x8c, 0x01, 0x0a, 0x0f, 0x52, 0x65, 0x70,
	0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x12, 0x29, 0x2e, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x52, 0x65, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63,
	0x6f, 0x73, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x70, 0x6f,
	0x70, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x22, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1c, 0x22, 0x1a, 0x2f, 0x76, 0x31,
	0x2f, 0x74, 0x61, 0x73, 0x6b, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x2d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x42, 0x2a, 0x5a, 0x28, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x3b, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73,
	0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infra_cros_fleetcost_api_rpc_service_proto_rawDescOnce sync.Once
	file_infra_cros_fleetcost_api_rpc_service_proto_rawDescData = file_infra_cros_fleetcost_api_rpc_service_proto_rawDesc
)

func file_infra_cros_fleetcost_api_rpc_service_proto_rawDescGZIP() []byte {
	file_infra_cros_fleetcost_api_rpc_service_proto_rawDescOnce.Do(func() {
		file_infra_cros_fleetcost_api_rpc_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_infra_cros_fleetcost_api_rpc_service_proto_rawDescData)
	})
	return file_infra_cros_fleetcost_api_rpc_service_proto_rawDescData
}

var file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_infra_cros_fleetcost_api_rpc_service_proto_goTypes = []interface{}{
	(*PingRequest)(nil),                 // 0: fleetcost.api.rpc.PingRequest
	(*PingResponse)(nil),                // 1: fleetcost.api.rpc.PingResponse
	(*PingUFSRequest)(nil),              // 2: fleetcost.api.rpc.PingUFSRequest
	(*PingUFSResponse)(nil),             // 3: fleetcost.api.rpc.PingUFSResponse
	(*CreateCostIndicatorRequest)(nil),  // 4: fleetcost.api.rpc.CreateCostIndicatorRequest
	(*CreateCostIndicatorResponse)(nil), // 5: fleetcost.api.rpc.CreateCostIndicatorResponse
	(*ListCostIndicatorsRequest)(nil),   // 6: fleetcost.api.rpc.ListCostIndicatorsRequest
	(*ListCostIndicatorsFilter)(nil),    // 7: fleetcost.api.rpc.ListCostIndicatorsFilter
	(*ListCostIndicatorsResponse)(nil),  // 8: fleetcost.api.rpc.ListCostIndicatorsResponse
	(*UpdateCostIndicatorRequest)(nil),  // 9: fleetcost.api.rpc.UpdateCostIndicatorRequest
	(*UpdateCostIndicatorResponse)(nil), // 10: fleetcost.api.rpc.UpdateCostIndicatorResponse
	(*GetCostResultRequest)(nil),        // 11: fleetcost.api.rpc.GetCostResultRequest
	(*GetCostResultResponse)(nil),       // 12: fleetcost.api.rpc.GetCostResultResponse
	(*DeleteCostIndicatorRequest)(nil),  // 13: fleetcost.api.rpc.DeleteCostIndicatorRequest
	(*DeleteCostIndicatorResponse)(nil), // 14: fleetcost.api.rpc.DeleteCostIndicatorResponse
	(*PersistToBigqueryRequest)(nil),    // 15: fleetcost.api.rpc.PersistToBigqueryRequest
	(*PersistToBigqueryResponse)(nil),   // 16: fleetcost.api.rpc.PersistToBigqueryResponse
	(*RepopulateCacheRequest)(nil),      // 17: fleetcost.api.rpc.RepopulateCacheRequest
	(*RepopulateCacheResponse)(nil),     // 18: fleetcost.api.rpc.RepopulateCacheResponse
	(*CreateVariableRequest)(nil),       // 19: fleetcost.api.rpc.CreateVariableRequest
	(*CreateVariableResponse)(nil),      // 20: fleetcost.api.rpc.CreateVariableResponse
	(*anypb.Any)(nil),                   // 21: google.protobuf.Any
	(*models.CostIndicator)(nil),        // 22: fleetcost.api.models.CostIndicator
	(*fieldmaskpb.FieldMask)(nil),       // 23: google.protobuf.FieldMask
	(*models.CostResult)(nil),           // 24: fleetcost.api.models.CostResult
	(*models.CostReport)(nil),           // 25: fleetcost.api.models.CostReport
	(*models.Variable)(nil),             // 26: fleetcost.api.models.Variable
}
var file_infra_cros_fleetcost_api_rpc_service_proto_depIdxs = []int32{
	21, // 0: fleetcost.api.rpc.PingUFSResponse.ufs_request:type_name -> google.protobuf.Any
	21, // 1: fleetcost.api.rpc.PingUFSResponse.ufs_response:type_name -> google.protobuf.Any
	22, // 2: fleetcost.api.rpc.CreateCostIndicatorRequest.cost_indicator:type_name -> fleetcost.api.models.CostIndicator
	22, // 3: fleetcost.api.rpc.CreateCostIndicatorResponse.cost_indicator:type_name -> fleetcost.api.models.CostIndicator
	7,  // 4: fleetcost.api.rpc.ListCostIndicatorsRequest.filter:type_name -> fleetcost.api.rpc.ListCostIndicatorsFilter
	22, // 5: fleetcost.api.rpc.ListCostIndicatorsResponse.cost_indicator:type_name -> fleetcost.api.models.CostIndicator
	22, // 6: fleetcost.api.rpc.UpdateCostIndicatorRequest.cost_indicator:type_name -> fleetcost.api.models.CostIndicator
	23, // 7: fleetcost.api.rpc.UpdateCostIndicatorRequest.update_mask:type_name -> google.protobuf.FieldMask
	22, // 8: fleetcost.api.rpc.UpdateCostIndicatorResponse.cost_indicator:type_name -> fleetcost.api.models.CostIndicator
	24, // 9: fleetcost.api.rpc.GetCostResultResponse.result:type_name -> fleetcost.api.models.CostResult
	25, // 10: fleetcost.api.rpc.GetCostResultResponse.report:type_name -> fleetcost.api.models.CostReport
	22, // 11: fleetcost.api.rpc.DeleteCostIndicatorRequest.cost_indicator:type_name -> fleetcost.api.models.CostIndicator
	22, // 12: fleetcost.api.rpc.DeleteCostIndicatorResponse.cost_indicator:type_name -> fleetcost.api.models.CostIndicator
	26, // 13: fleetcost.api.rpc.CreateVariableRequest.variable:type_name -> fleetcost.api.models.Variable
	26, // 14: fleetcost.api.rpc.CreateVariableResponse.variable:type_name -> fleetcost.api.models.Variable
	0,  // 15: fleetcost.api.rpc.FleetCost.Ping:input_type -> fleetcost.api.rpc.PingRequest
	2,  // 16: fleetcost.api.rpc.FleetCost.PingUFS:input_type -> fleetcost.api.rpc.PingUFSRequest
	4,  // 17: fleetcost.api.rpc.FleetCost.CreateCostIndicator:input_type -> fleetcost.api.rpc.CreateCostIndicatorRequest
	6,  // 18: fleetcost.api.rpc.FleetCost.ListCostIndicators:input_type -> fleetcost.api.rpc.ListCostIndicatorsRequest
	9,  // 19: fleetcost.api.rpc.FleetCost.UpdateCostIndicator:input_type -> fleetcost.api.rpc.UpdateCostIndicatorRequest
	13, // 20: fleetcost.api.rpc.FleetCost.DeleteCostIndicator:input_type -> fleetcost.api.rpc.DeleteCostIndicatorRequest
	19, // 21: fleetcost.api.rpc.FleetCost.CreateVariable:input_type -> fleetcost.api.rpc.CreateVariableRequest
	11, // 22: fleetcost.api.rpc.FleetCost.GetCostResult:input_type -> fleetcost.api.rpc.GetCostResultRequest
	15, // 23: fleetcost.api.rpc.FleetCost.PersistToBigquery:input_type -> fleetcost.api.rpc.PersistToBigqueryRequest
	17, // 24: fleetcost.api.rpc.FleetCost.RepopulateCache:input_type -> fleetcost.api.rpc.RepopulateCacheRequest
	1,  // 25: fleetcost.api.rpc.FleetCost.Ping:output_type -> fleetcost.api.rpc.PingResponse
	3,  // 26: fleetcost.api.rpc.FleetCost.PingUFS:output_type -> fleetcost.api.rpc.PingUFSResponse
	5,  // 27: fleetcost.api.rpc.FleetCost.CreateCostIndicator:output_type -> fleetcost.api.rpc.CreateCostIndicatorResponse
	8,  // 28: fleetcost.api.rpc.FleetCost.ListCostIndicators:output_type -> fleetcost.api.rpc.ListCostIndicatorsResponse
	10, // 29: fleetcost.api.rpc.FleetCost.UpdateCostIndicator:output_type -> fleetcost.api.rpc.UpdateCostIndicatorResponse
	14, // 30: fleetcost.api.rpc.FleetCost.DeleteCostIndicator:output_type -> fleetcost.api.rpc.DeleteCostIndicatorResponse
	20, // 31: fleetcost.api.rpc.FleetCost.CreateVariable:output_type -> fleetcost.api.rpc.CreateVariableResponse
	12, // 32: fleetcost.api.rpc.FleetCost.GetCostResult:output_type -> fleetcost.api.rpc.GetCostResultResponse
	16, // 33: fleetcost.api.rpc.FleetCost.PersistToBigquery:output_type -> fleetcost.api.rpc.PersistToBigqueryResponse
	18, // 34: fleetcost.api.rpc.FleetCost.RepopulateCache:output_type -> fleetcost.api.rpc.RepopulateCacheResponse
	25, // [25:35] is the sub-list for method output_type
	15, // [15:25] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_infra_cros_fleetcost_api_rpc_service_proto_init() }
func file_infra_cros_fleetcost_api_rpc_service_proto_init() {
	if File_infra_cros_fleetcost_api_rpc_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingUFSRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingUFSResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCostIndicatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateCostIndicatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCostIndicatorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCostIndicatorsFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCostIndicatorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCostIndicatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateCostIndicatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCostResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCostResultResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCostIndicatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteCostIndicatorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersistToBigqueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersistToBigqueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepopulateCacheRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepopulateCacheResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVariableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVariableResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infra_cros_fleetcost_api_rpc_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_infra_cros_fleetcost_api_rpc_service_proto_goTypes,
		DependencyIndexes: file_infra_cros_fleetcost_api_rpc_service_proto_depIdxs,
		MessageInfos:      file_infra_cros_fleetcost_api_rpc_service_proto_msgTypes,
	}.Build()
	File_infra_cros_fleetcost_api_rpc_service_proto = out.File
	file_infra_cros_fleetcost_api_rpc_service_proto_rawDesc = nil
	file_infra_cros_fleetcost_api_rpc_service_proto_goTypes = nil
	file_infra_cros_fleetcost_api_rpc_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FleetCostClient is the client API for FleetCost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FleetCostClient interface {
	// Ping does not send or receive any information. It just checks that the service is there.
	//
	// It can't be given any data and does not return anything especially useful.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// PingUFS pings UFS and returns what it did.
	PingUFS(ctx context.Context, in *PingUFSRequest, opts ...grpc.CallOption) (*PingUFSResponse, error)
	// CreateCostIndicator creates a new cost indicator.
	CreateCostIndicator(ctx context.Context, in *CreateCostIndicatorRequest, opts ...grpc.CallOption) (*CreateCostIndicatorResponse, error)
	// ListCostIndicators creates a new cost indicator.
	ListCostIndicators(ctx context.Context, in *ListCostIndicatorsRequest, opts ...grpc.CallOption) (*ListCostIndicatorsResponse, error)
	// UpdateCostIndicator updates an existing cost indicator.
	UpdateCostIndicator(ctx context.Context, in *UpdateCostIndicatorRequest, opts ...grpc.CallOption) (*UpdateCostIndicatorResponse, error)
	DeleteCostIndicator(ctx context.Context, in *DeleteCostIndicatorRequest, opts ...grpc.CallOption) (*DeleteCostIndicatorResponse, error)
	// CreateVariable creates a variable for storing non-cost data.
	CreateVariable(ctx context.Context, in *CreateVariableRequest, opts ...grpc.CallOption) (*CreateVariableResponse, error)
	// GetCostResult gets the cost breakdown for a given device.
	GetCostResult(ctx context.Context, in *GetCostResultRequest, opts ...grpc.CallOption) (*GetCostResultResponse, error)
	// PeristToBigquery persists records to BigQuery.
	PersistToBigquery(ctx context.Context, in *PersistToBigqueryRequest, opts ...grpc.CallOption) (*PersistToBigqueryResponse, error)
	// RepopulateCache ensures that the cost data matches the state of UFS.
	RepopulateCache(ctx context.Context, in *RepopulateCacheRequest, opts ...grpc.CallOption) (*RepopulateCacheResponse, error)
}
type fleetCostPRPCClient struct {
	client *prpc.Client
}

func NewFleetCostPRPCClient(client *prpc.Client) FleetCostClient {
	return &fleetCostPRPCClient{client}
}

func (c *fleetCostPRPCClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.client.Call(ctx, "fleetcost.api.rpc.FleetCost", "Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostPRPCClient) PingUFS(ctx context.Context, in *PingUFSRequest, opts ...grpc.CallOption) (*PingUFSResponse, error) {
	out := new(PingUFSResponse)
	err := c.client.Call(ctx, "fleetcost.api.rpc.FleetCost", "PingUFS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostPRPCClient) CreateCostIndicator(ctx context.Context, in *CreateCostIndicatorRequest, opts ...grpc.CallOption) (*CreateCostIndicatorResponse, error) {
	out := new(CreateCostIndicatorResponse)
	err := c.client.Call(ctx, "fleetcost.api.rpc.FleetCost", "CreateCostIndicator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostPRPCClient) ListCostIndicators(ctx context.Context, in *ListCostIndicatorsRequest, opts ...grpc.CallOption) (*ListCostIndicatorsResponse, error) {
	out := new(ListCostIndicatorsResponse)
	err := c.client.Call(ctx, "fleetcost.api.rpc.FleetCost", "ListCostIndicators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostPRPCClient) UpdateCostIndicator(ctx context.Context, in *UpdateCostIndicatorRequest, opts ...grpc.CallOption) (*UpdateCostIndicatorResponse, error) {
	out := new(UpdateCostIndicatorResponse)
	err := c.client.Call(ctx, "fleetcost.api.rpc.FleetCost", "UpdateCostIndicator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostPRPCClient) DeleteCostIndicator(ctx context.Context, in *DeleteCostIndicatorRequest, opts ...grpc.CallOption) (*DeleteCostIndicatorResponse, error) {
	out := new(DeleteCostIndicatorResponse)
	err := c.client.Call(ctx, "fleetcost.api.rpc.FleetCost", "DeleteCostIndicator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostPRPCClient) CreateVariable(ctx context.Context, in *CreateVariableRequest, opts ...grpc.CallOption) (*CreateVariableResponse, error) {
	out := new(CreateVariableResponse)
	err := c.client.Call(ctx, "fleetcost.api.rpc.FleetCost", "CreateVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostPRPCClient) GetCostResult(ctx context.Context, in *GetCostResultRequest, opts ...grpc.CallOption) (*GetCostResultResponse, error) {
	out := new(GetCostResultResponse)
	err := c.client.Call(ctx, "fleetcost.api.rpc.FleetCost", "GetCostResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostPRPCClient) PersistToBigquery(ctx context.Context, in *PersistToBigqueryRequest, opts ...grpc.CallOption) (*PersistToBigqueryResponse, error) {
	out := new(PersistToBigqueryResponse)
	err := c.client.Call(ctx, "fleetcost.api.rpc.FleetCost", "PersistToBigquery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostPRPCClient) RepopulateCache(ctx context.Context, in *RepopulateCacheRequest, opts ...grpc.CallOption) (*RepopulateCacheResponse, error) {
	out := new(RepopulateCacheResponse)
	err := c.client.Call(ctx, "fleetcost.api.rpc.FleetCost", "RepopulateCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type fleetCostClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetCostClient(cc grpc.ClientConnInterface) FleetCostClient {
	return &fleetCostClient{cc}
}

func (c *fleetCostClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/fleetcost.api.rpc.FleetCost/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostClient) PingUFS(ctx context.Context, in *PingUFSRequest, opts ...grpc.CallOption) (*PingUFSResponse, error) {
	out := new(PingUFSResponse)
	err := c.cc.Invoke(ctx, "/fleetcost.api.rpc.FleetCost/PingUFS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostClient) CreateCostIndicator(ctx context.Context, in *CreateCostIndicatorRequest, opts ...grpc.CallOption) (*CreateCostIndicatorResponse, error) {
	out := new(CreateCostIndicatorResponse)
	err := c.cc.Invoke(ctx, "/fleetcost.api.rpc.FleetCost/CreateCostIndicator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostClient) ListCostIndicators(ctx context.Context, in *ListCostIndicatorsRequest, opts ...grpc.CallOption) (*ListCostIndicatorsResponse, error) {
	out := new(ListCostIndicatorsResponse)
	err := c.cc.Invoke(ctx, "/fleetcost.api.rpc.FleetCost/ListCostIndicators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostClient) UpdateCostIndicator(ctx context.Context, in *UpdateCostIndicatorRequest, opts ...grpc.CallOption) (*UpdateCostIndicatorResponse, error) {
	out := new(UpdateCostIndicatorResponse)
	err := c.cc.Invoke(ctx, "/fleetcost.api.rpc.FleetCost/UpdateCostIndicator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostClient) DeleteCostIndicator(ctx context.Context, in *DeleteCostIndicatorRequest, opts ...grpc.CallOption) (*DeleteCostIndicatorResponse, error) {
	out := new(DeleteCostIndicatorResponse)
	err := c.cc.Invoke(ctx, "/fleetcost.api.rpc.FleetCost/DeleteCostIndicator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostClient) CreateVariable(ctx context.Context, in *CreateVariableRequest, opts ...grpc.CallOption) (*CreateVariableResponse, error) {
	out := new(CreateVariableResponse)
	err := c.cc.Invoke(ctx, "/fleetcost.api.rpc.FleetCost/CreateVariable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostClient) GetCostResult(ctx context.Context, in *GetCostResultRequest, opts ...grpc.CallOption) (*GetCostResultResponse, error) {
	out := new(GetCostResultResponse)
	err := c.cc.Invoke(ctx, "/fleetcost.api.rpc.FleetCost/GetCostResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostClient) PersistToBigquery(ctx context.Context, in *PersistToBigqueryRequest, opts ...grpc.CallOption) (*PersistToBigqueryResponse, error) {
	out := new(PersistToBigqueryResponse)
	err := c.cc.Invoke(ctx, "/fleetcost.api.rpc.FleetCost/PersistToBigquery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetCostClient) RepopulateCache(ctx context.Context, in *RepopulateCacheRequest, opts ...grpc.CallOption) (*RepopulateCacheResponse, error) {
	out := new(RepopulateCacheResponse)
	err := c.cc.Invoke(ctx, "/fleetcost.api.rpc.FleetCost/RepopulateCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetCostServer is the server API for FleetCost service.
type FleetCostServer interface {
	// Ping does not send or receive any information. It just checks that the service is there.
	//
	// It can't be given any data and does not return anything especially useful.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// PingUFS pings UFS and returns what it did.
	PingUFS(context.Context, *PingUFSRequest) (*PingUFSResponse, error)
	// CreateCostIndicator creates a new cost indicator.
	CreateCostIndicator(context.Context, *CreateCostIndicatorRequest) (*CreateCostIndicatorResponse, error)
	// ListCostIndicators creates a new cost indicator.
	ListCostIndicators(context.Context, *ListCostIndicatorsRequest) (*ListCostIndicatorsResponse, error)
	// UpdateCostIndicator updates an existing cost indicator.
	UpdateCostIndicator(context.Context, *UpdateCostIndicatorRequest) (*UpdateCostIndicatorResponse, error)
	DeleteCostIndicator(context.Context, *DeleteCostIndicatorRequest) (*DeleteCostIndicatorResponse, error)
	// CreateVariable creates a variable for storing non-cost data.
	CreateVariable(context.Context, *CreateVariableRequest) (*CreateVariableResponse, error)
	// GetCostResult gets the cost breakdown for a given device.
	GetCostResult(context.Context, *GetCostResultRequest) (*GetCostResultResponse, error)
	// PeristToBigquery persists records to BigQuery.
	PersistToBigquery(context.Context, *PersistToBigqueryRequest) (*PersistToBigqueryResponse, error)
	// RepopulateCache ensures that the cost data matches the state of UFS.
	RepopulateCache(context.Context, *RepopulateCacheRequest) (*RepopulateCacheResponse, error)
}

// UnimplementedFleetCostServer can be embedded to have forward compatible implementations.
type UnimplementedFleetCostServer struct {
}

func (*UnimplementedFleetCostServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedFleetCostServer) PingUFS(context.Context, *PingUFSRequest) (*PingUFSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingUFS not implemented")
}
func (*UnimplementedFleetCostServer) CreateCostIndicator(context.Context, *CreateCostIndicatorRequest) (*CreateCostIndicatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCostIndicator not implemented")
}
func (*UnimplementedFleetCostServer) ListCostIndicators(context.Context, *ListCostIndicatorsRequest) (*ListCostIndicatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCostIndicators not implemented")
}
func (*UnimplementedFleetCostServer) UpdateCostIndicator(context.Context, *UpdateCostIndicatorRequest) (*UpdateCostIndicatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCostIndicator not implemented")
}
func (*UnimplementedFleetCostServer) DeleteCostIndicator(context.Context, *DeleteCostIndicatorRequest) (*DeleteCostIndicatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCostIndicator not implemented")
}
func (*UnimplementedFleetCostServer) CreateVariable(context.Context, *CreateVariableRequest) (*CreateVariableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVariable not implemented")
}
func (*UnimplementedFleetCostServer) GetCostResult(context.Context, *GetCostResultRequest) (*GetCostResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCostResult not implemented")
}
func (*UnimplementedFleetCostServer) PersistToBigquery(context.Context, *PersistToBigqueryRequest) (*PersistToBigqueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PersistToBigquery not implemented")
}
func (*UnimplementedFleetCostServer) RepopulateCache(context.Context, *RepopulateCacheRequest) (*RepopulateCacheResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RepopulateCache not implemented")
}

func RegisterFleetCostServer(s prpc.Registrar, srv FleetCostServer) {
	s.RegisterService(&_FleetCost_serviceDesc, srv)
}

func _FleetCost_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCostServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleetcost.api.rpc.FleetCost/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCostServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetCost_PingUFS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingUFSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCostServer).PingUFS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleetcost.api.rpc.FleetCost/PingUFS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCostServer).PingUFS(ctx, req.(*PingUFSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetCost_CreateCostIndicator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCostIndicatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCostServer).CreateCostIndicator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleetcost.api.rpc.FleetCost/CreateCostIndicator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCostServer).CreateCostIndicator(ctx, req.(*CreateCostIndicatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetCost_ListCostIndicators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCostIndicatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCostServer).ListCostIndicators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleetcost.api.rpc.FleetCost/ListCostIndicators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCostServer).ListCostIndicators(ctx, req.(*ListCostIndicatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetCost_UpdateCostIndicator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCostIndicatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCostServer).UpdateCostIndicator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleetcost.api.rpc.FleetCost/UpdateCostIndicator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCostServer).UpdateCostIndicator(ctx, req.(*UpdateCostIndicatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetCost_DeleteCostIndicator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCostIndicatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCostServer).DeleteCostIndicator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleetcost.api.rpc.FleetCost/DeleteCostIndicator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCostServer).DeleteCostIndicator(ctx, req.(*DeleteCostIndicatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetCost_CreateVariable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVariableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCostServer).CreateVariable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleetcost.api.rpc.FleetCost/CreateVariable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCostServer).CreateVariable(ctx, req.(*CreateVariableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetCost_GetCostResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCostResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCostServer).GetCostResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleetcost.api.rpc.FleetCost/GetCostResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCostServer).GetCostResult(ctx, req.(*GetCostResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetCost_PersistToBigquery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersistToBigqueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCostServer).PersistToBigquery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleetcost.api.rpc.FleetCost/PersistToBigquery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCostServer).PersistToBigquery(ctx, req.(*PersistToBigqueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetCost_RepopulateCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepopulateCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetCostServer).RepopulateCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleetcost.api.rpc.FleetCost/RepopulateCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetCostServer).RepopulateCache(ctx, req.(*RepopulateCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FleetCost_serviceDesc = grpc.ServiceDesc{
	ServiceName: "fleetcost.api.rpc.FleetCost",
	HandlerType: (*FleetCostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _FleetCost_Ping_Handler,
		},
		{
			MethodName: "PingUFS",
			Handler:    _FleetCost_PingUFS_Handler,
		},
		{
			MethodName: "CreateCostIndicator",
			Handler:    _FleetCost_CreateCostIndicator_Handler,
		},
		{
			MethodName: "ListCostIndicators",
			Handler:    _FleetCost_ListCostIndicators_Handler,
		},
		{
			MethodName: "UpdateCostIndicator",
			Handler:    _FleetCost_UpdateCostIndicator_Handler,
		},
		{
			MethodName: "DeleteCostIndicator",
			Handler:    _FleetCost_DeleteCostIndicator_Handler,
		},
		{
			MethodName: "CreateVariable",
			Handler:    _FleetCost_CreateVariable_Handler,
		},
		{
			MethodName: "GetCostResult",
			Handler:    _FleetCost_GetCostResult_Handler,
		},
		{
			MethodName: "PersistToBigquery",
			Handler:    _FleetCost_PersistToBigquery_Handler,
		},
		{
			MethodName: "RepopulateCache",
			Handler:    _FleetCost_RepopulateCache_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "infra/cros/fleetcost/api/rpc/service.proto",
}
