// Copyright 2025 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: infra/unifiedfleet/api/v1/models/maintenance_config.proto

package ufspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Defines configurations – user defined or default – for a group of bots.
// The configurations are used to create a dashboard for SLOs.
type MaintenanceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the maintenance configuration. should be unique/succinct
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Emails of owners of these bots. Optional.
	Owners []string `protobuf:"bytes,2,rep,name=owners,proto3" json:"owners,omitempty"`
	// An enumeration of bot IDs belonging to this group
	BotId []string `protobuf:"bytes,3,rep,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	// A prefix to match against bot ID string. Optional
	BotIdPrefix []string `protobuf:"bytes,4,rep,name=bot_id_prefix,json=botIdPrefix,proto3" json:"bot_id_prefix,omitempty"`
	// The dimensions assigned to these bots
	Dimensions    []string                        `protobuf:"bytes,5,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	ServiceLevel  *MaintenanceConfig_ServiceLevel `protobuf:"bytes,6,opt,name=service_level,json=serviceLevel,proto3" json:"service_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceConfig) Reset() {
	*x = MaintenanceConfig{}
	mi := &file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceConfig) ProtoMessage() {}

func (x *MaintenanceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceConfig.ProtoReflect.Descriptor instead.
func (*MaintenanceConfig) Descriptor() ([]byte, []int) {
	return file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDescGZIP(), []int{0}
}

func (x *MaintenanceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MaintenanceConfig) GetOwners() []string {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *MaintenanceConfig) GetBotId() []string {
	if x != nil {
		return x.BotId
	}
	return nil
}

func (x *MaintenanceConfig) GetBotIdPrefix() []string {
	if x != nil {
		return x.BotIdPrefix
	}
	return nil
}

func (x *MaintenanceConfig) GetDimensions() []string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *MaintenanceConfig) GetServiceLevel() *MaintenanceConfig_ServiceLevel {
	if x != nil {
		return x.ServiceLevel
	}
	return nil
}

// List maintenance configurations for each bots group
type MaintenanceConfigs struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaintenanceConfig []*MaintenanceConfig   `protobuf:"bytes,1,rep,name=maintenance_config,json=maintenanceConfig,proto3" json:"maintenance_config,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MaintenanceConfigs) Reset() {
	*x = MaintenanceConfigs{}
	mi := &file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceConfigs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceConfigs) ProtoMessage() {}

func (x *MaintenanceConfigs) ProtoReflect() protoreflect.Message {
	mi := &file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceConfigs.ProtoReflect.Descriptor instead.
func (*MaintenanceConfigs) Descriptor() ([]byte, []int) {
	return file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDescGZIP(), []int{1}
}

func (x *MaintenanceConfigs) GetMaintenanceConfig() []*MaintenanceConfig {
	if x != nil {
		return x.MaintenanceConfig
	}
	return nil
}

// Defines the slo requirements for this maintenance configuration
type MaintenanceConfig_ServiceLevel struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Desciption      string                 `protobuf:"bytes,1,opt,name=desciption,proto3" json:"desciption,omitempty"`
	IsSlo           bool                   `protobuf:"varint,2,opt,name=is_slo,json=isSlo,proto3" json:"is_slo,omitempty"`
	MinAvailability uint32                 `protobuf:"varint,3,opt,name=min_availability,json=minAvailability,proto3" json:"min_availability,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MaintenanceConfig_ServiceLevel) Reset() {
	*x = MaintenanceConfig_ServiceLevel{}
	mi := &file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceConfig_ServiceLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceConfig_ServiceLevel) ProtoMessage() {}

func (x *MaintenanceConfig_ServiceLevel) ProtoReflect() protoreflect.Message {
	mi := &file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceConfig_ServiceLevel.ProtoReflect.Descriptor instead.
func (*MaintenanceConfig_ServiceLevel) Descriptor() ([]byte, []int) {
	return file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDescGZIP(), []int{0, 0}
}

func (x *MaintenanceConfig_ServiceLevel) GetDesciption() string {
	if x != nil {
		return x.Desciption
	}
	return ""
}

func (x *MaintenanceConfig_ServiceLevel) GetIsSlo() bool {
	if x != nil {
		return x.IsSlo
	}
	return false
}

func (x *MaintenanceConfig_ServiceLevel) GetMinAvailability() uint32 {
	if x != nil {
		return x.MinAvailability
	}
	return 0
}

var File_infra_unifiedfleet_api_v1_models_maintenance_config_proto protoreflect.FileDescriptor

var file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDesc = []byte{
	0x0a, 0x39, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x75, 0x6e, 0x69,
	0x66, 0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0xed, 0x02, 0x0a, 0x11, 0x4d, 0x61, 0x69, 0x6e,
	0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x6f, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x74, 0x49, 0x64,
	0x12, 0x22, 0x0a, 0x0d, 0x62, 0x6f, 0x74, 0x5f, 0x69, 0x64, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x6f, 0x74, 0x49, 0x64, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x5f, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x75, 0x6e,
	0x69, 0x66, 0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e,
	0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x1a, 0x70, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x73, 0x63, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x64, 0x65, 0x73, 0x63, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x73, 0x6c, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x69, 0x73, 0x53, 0x6c, 0x6f, 0x12, 0x29, 0x0a, 0x10,
	0x6d, 0x69, 0x6e, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x6d, 0x69, 0x6e, 0x41, 0x76, 0x61, 0x69, 0x6c,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x72, 0x0a, 0x12, 0x4d, 0x61, 0x69, 0x6e, 0x74,
	0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x12, 0x5c, 0x0a,
	0x12, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x75, 0x6e, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4d, 0x61, 0x69, 0x6e, 0x74, 0x65, 0x6e, 0x61, 0x6e,
	0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x11, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x65,
	0x6e, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x28, 0x5a, 0x26, 0x69,
	0x6e, 0x66, 0x72, 0x61, 0x2f, 0x75, 0x6e, 0x69, 0x66, 0x69, 0x65, 0x64, 0x66, 0x6c, 0x65, 0x65,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x3b,
	0x75, 0x66, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDescOnce sync.Once
	file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDescData = file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDesc
)

func file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDescGZIP() []byte {
	file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDescOnce.Do(func() {
		file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDescData)
	})
	return file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDescData
}

var file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_goTypes = []any{
	(*MaintenanceConfig)(nil),              // 0: unifiedfleet.api.v1.models.MaintenanceConfig
	(*MaintenanceConfigs)(nil),             // 1: unifiedfleet.api.v1.models.MaintenanceConfigs
	(*MaintenanceConfig_ServiceLevel)(nil), // 2: unifiedfleet.api.v1.models.MaintenanceConfig.ServiceLevel
}
var file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_depIdxs = []int32{
	2, // 0: unifiedfleet.api.v1.models.MaintenanceConfig.service_level:type_name -> unifiedfleet.api.v1.models.MaintenanceConfig.ServiceLevel
	0, // 1: unifiedfleet.api.v1.models.MaintenanceConfigs.maintenance_config:type_name -> unifiedfleet.api.v1.models.MaintenanceConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_init() }
func file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_init() {
	if File_infra_unifiedfleet_api_v1_models_maintenance_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_goTypes,
		DependencyIndexes: file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_depIdxs,
		MessageInfos:      file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_msgTypes,
	}.Build()
	File_infra_unifiedfleet_api_v1_models_maintenance_config_proto = out.File
	file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_rawDesc = nil
	file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_goTypes = nil
	file_infra_unifiedfleet_api_v1_models_maintenance_config_proto_depIdxs = nil
}
