// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: infra/cros/fleetcost/api/models/cost_report.proto

package fleetcostpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CostReport is a breakdown of the subtotals of cost.
type CostReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item []*CostReportItem `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
}

func (x *CostReport) Reset() {
	*x = CostReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_models_cost_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CostReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostReport) ProtoMessage() {}

func (x *CostReport) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_models_cost_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostReport.ProtoReflect.Descriptor instead.
func (*CostReport) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_models_cost_report_proto_rawDescGZIP(), []int{0}
}

func (x *CostReport) GetItem() []*CostReportItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// CostReportItem is a subtotal within the ultimate CostResult.
type CostReportItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubtotalName    string  `protobuf:"bytes,1,opt,name=subtotal_name,json=subtotalName,proto3" json:"subtotal_name,omitempty"`
	RawFigure       float64 `protobuf:"fixed64,2,opt,name=raw_figure,json=rawFigure,proto3" json:"raw_figure,omitempty"`
	PerDeviceFigure float64 `protobuf:"fixed64,3,opt,name=per_device_figure,json=perDeviceFigure,proto3" json:"per_device_figure,omitempty"`
	// categories are:
	// - "dedicated"
	// - "shared"
	// - "cloud"
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *CostReportItem) Reset() {
	*x = CostReportItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infra_cros_fleetcost_api_models_cost_report_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CostReportItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostReportItem) ProtoMessage() {}

func (x *CostReportItem) ProtoReflect() protoreflect.Message {
	mi := &file_infra_cros_fleetcost_api_models_cost_report_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostReportItem.ProtoReflect.Descriptor instead.
func (*CostReportItem) Descriptor() ([]byte, []int) {
	return file_infra_cros_fleetcost_api_models_cost_report_proto_rawDescGZIP(), []int{1}
}

func (x *CostReportItem) GetSubtotalName() string {
	if x != nil {
		return x.SubtotalName
	}
	return ""
}

func (x *CostReportItem) GetRawFigure() float64 {
	if x != nil {
		return x.RawFigure
	}
	return 0
}

func (x *CostReportItem) GetPerDeviceFigure() float64 {
	if x != nil {
		return x.PerDeviceFigure
	}
	return 0
}

func (x *CostReportItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

var File_infra_cros_fleetcost_api_models_cost_report_proto protoreflect.FileDescriptor

var file_infra_cros_fleetcost_api_models_cost_report_proto_rawDesc = []byte{
	0x0a, 0x31, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x66, 0x6c, 0x65,
	0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x63, 0x6f, 0x73, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0x46, 0x0a, 0x0a, 0x43, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x38, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73,
	0x74, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x43, 0x6f, 0x73,
	0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65,
	0x6d, 0x22, 0x9c, 0x01, 0x0a, 0x0e, 0x43, 0x6f, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x75, 0x62, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75, 0x62,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x61, 0x77,
	0x5f, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09, 0x72,
	0x61, 0x77, 0x46, 0x69, 0x67, 0x75, 0x72, 0x65, 0x12, 0x2a, 0x0a, 0x11, 0x70, 0x65, 0x72, 0x5f,
	0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x0f, 0x70, 0x65, 0x72, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x46, 0x69,
	0x67, 0x75, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x42, 0x2d, 0x5a, 0x2b, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x63, 0x72, 0x6f, 0x73, 0x2f, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x3b, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x73, 0x74, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infra_cros_fleetcost_api_models_cost_report_proto_rawDescOnce sync.Once
	file_infra_cros_fleetcost_api_models_cost_report_proto_rawDescData = file_infra_cros_fleetcost_api_models_cost_report_proto_rawDesc
)

func file_infra_cros_fleetcost_api_models_cost_report_proto_rawDescGZIP() []byte {
	file_infra_cros_fleetcost_api_models_cost_report_proto_rawDescOnce.Do(func() {
		file_infra_cros_fleetcost_api_models_cost_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_infra_cros_fleetcost_api_models_cost_report_proto_rawDescData)
	})
	return file_infra_cros_fleetcost_api_models_cost_report_proto_rawDescData
}

var file_infra_cros_fleetcost_api_models_cost_report_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_infra_cros_fleetcost_api_models_cost_report_proto_goTypes = []interface{}{
	(*CostReport)(nil),     // 0: fleetcost.api.models.CostReport
	(*CostReportItem)(nil), // 1: fleetcost.api.models.CostReportItem
}
var file_infra_cros_fleetcost_api_models_cost_report_proto_depIdxs = []int32{
	1, // 0: fleetcost.api.models.CostReport.item:type_name -> fleetcost.api.models.CostReportItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_infra_cros_fleetcost_api_models_cost_report_proto_init() }
func file_infra_cros_fleetcost_api_models_cost_report_proto_init() {
	if File_infra_cros_fleetcost_api_models_cost_report_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_infra_cros_fleetcost_api_models_cost_report_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CostReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_infra_cros_fleetcost_api_models_cost_report_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CostReportItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infra_cros_fleetcost_api_models_cost_report_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infra_cros_fleetcost_api_models_cost_report_proto_goTypes,
		DependencyIndexes: file_infra_cros_fleetcost_api_models_cost_report_proto_depIdxs,
		MessageInfos:      file_infra_cros_fleetcost_api_models_cost_report_proto_msgTypes,
	}.Build()
	File_infra_cros_fleetcost_api_models_cost_report_proto = out.File
	file_infra_cros_fleetcost_api_models_cost_report_proto_rawDesc = nil
	file_infra_cros_fleetcost_api_models_cost_report_proto_goTypes = nil
	file_infra_cros_fleetcost_api_models_cost_report_proto_depIdxs = nil
}
