# Explicitly turn off all tests that are currently failing in the infra tree.
#
# For more information on the meaning of these codes, see https://staticcheck.io/docs/checks.
checks = [
  "all",
  # Explicitly forgiven errors.

  "-ST1008",
  # The following function breaks the rule ST1008 by having the error value be non-last.
  # However, moving the cleanup function to be non-last results in stylistcally bad code, so this check is disabled forever.
  #
  # ```
  #   func setupContext(version string) (_ context.Context, _ error, cleanup func()) {
  #     ...
  #   }
  # ```
  #

  # Redundant printf usage.
  "-SA1006",

  # Use of deprecated API. Very common, including in generated code. This check can likely never be enabled.
  "-SA1019",

  # Error naming.
  "-ST1012",

  # Non-even number of arguments in a printf-like function. Needed for a unit test.
  "-SA5012",

  # use of sprintf-like functions in argument to errors.printf
  "-S1028",

  # Errors that have not been analyzed yet.
  "-S1000",
  "-S1001",
  "-S1002",
  "-S1004",
  "-S1005",
  "-S1006",
  "-S1007",
  "-S1008",
  "-S1009",
  "-S1011",
  "-S1012",
  "-S1016",
  "-S1017",
  "-S1021",
  "-S1023",
  "-S1024",
  "-S1025",
  "-S1030",
  "-S1031",
  "-S1032",
  "-S1034",
  "-S1038",
  "-S1039",
  "-SA1012",
  "-SA1015",
  "-SA1024",
  "-SA1029",
  "-SA4001",
  "-SA4006",
  "-SA4010",
  "-SA4011",
  "-SA4017",
  "-SA4021",
  "-SA4022",
  "-SA4023",
  "-SA4024",
  "-SA4031",
  "-SA5001",
  "-SA9001",
  "-SA9003",
  "-SA9004",
  "-ST1000",
  "-ST1001",
  "-ST1003",
  "-ST1005",
  "-ST1006",
  "-ST1011",
  "-ST1013",
  "-ST1016",
  "-ST1019",
  "-ST1020",
  "-ST1021",
  "-ST1022",
  "-ST1023",
  "-U1000",
]
