// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.3
// 	protoc        v5.29.3
// source: infra/fleetconsole/internal/internalproto/internalproto.proto

package internalproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The message represents ListDevices pagination token.
type ListDevicesPaginationToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesPaginationToken) Reset() {
	*x = ListDevicesPaginationToken{}
	mi := &file_infra_fleetconsole_internal_internalproto_internalproto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesPaginationToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesPaginationToken) ProtoMessage() {}

func (x *ListDevicesPaginationToken) ProtoReflect() protoreflect.Message {
	mi := &file_infra_fleetconsole_internal_internalproto_internalproto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesPaginationToken.ProtoReflect.Descriptor instead.
func (*ListDevicesPaginationToken) Descriptor() ([]byte, []int) {
	return file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDescGZIP(), []int{0}
}

func (x *ListDevicesPaginationToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_infra_fleetconsole_internal_internalproto_internalproto_proto protoreflect.FileDescriptor

var file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDesc = []byte{
	0x0a, 0x3d, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e,
	0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x66, 0x6c, 0x65, 0x65, 0x74, 0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x22, 0x32, 0x0a,
	0x1a, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x73, 0x50, 0x61, 0x67, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x42, 0x39, 0x5a, 0x37, 0x69, 0x6e, 0x66, 0x72, 0x61, 0x2f, 0x66, 0x6c, 0x65, 0x65, 0x74,
	0x63, 0x6f, 0x6e, 0x73, 0x6f, 0x6c, 0x65, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDescOnce sync.Once
	file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDescData = file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDesc
)

func file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDescGZIP() []byte {
	file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDescOnce.Do(func() {
		file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDescData = protoimpl.X.CompressGZIP(file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDescData)
	})
	return file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDescData
}

var file_infra_fleetconsole_internal_internalproto_internalproto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_infra_fleetconsole_internal_internalproto_internalproto_proto_goTypes = []any{
	(*ListDevicesPaginationToken)(nil), // 0: fleetconsole.ListDevicesPaginationToken
}
var file_infra_fleetconsole_internal_internalproto_internalproto_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_infra_fleetconsole_internal_internalproto_internalproto_proto_init() }
func file_infra_fleetconsole_internal_internalproto_internalproto_proto_init() {
	if File_infra_fleetconsole_internal_internalproto_internalproto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infra_fleetconsole_internal_internalproto_internalproto_proto_goTypes,
		DependencyIndexes: file_infra_fleetconsole_internal_internalproto_internalproto_proto_depIdxs,
		MessageInfos:      file_infra_fleetconsole_internal_internalproto_internalproto_proto_msgTypes,
	}.Build()
	File_infra_fleetconsole_internal_internalproto_internalproto_proto = out.File
	file_infra_fleetconsole_internal_internalproto_internalproto_proto_rawDesc = nil
	file_infra_fleetconsole_internal_internalproto_internalproto_proto_goTypes = nil
	file_infra_fleetconsole_internal_internalproto_internalproto_proto_depIdxs = nil
}
