# Generated by the pRPC protocol buffer compiler plugin.  DO NOT EDIT!
# source: go.chromium.org/luci/resultdb/proto/v1/schema.proto

import base64
import zlib

from google.protobuf import descriptor_pb2

# Includes description of the go.chromium.org/luci/resultdb/proto/v1/schema.proto and all of its transitive
# dependencies. Includes source code info.
FILE_DESCRIPTOR_SET = descriptor_pb2.FileDescriptorSet()
FILE_DESCRIPTOR_SET.ParseFromString(zlib.decompress(base64.b64decode(
    'eJztWM1yG8cR1gIQBY0UawQ5MYUo8gi2ZSmGFhKdqGKqUglFUQ5kmVSBpFS2y3YNsENgw8UutD'
    '+kkFQuvuboB8gb5OJcckpVKucc/Ap5h+Sar3sG4JIUY1UOOYXFomZ6evr3655eiX/dEO8PE38w'
    'SpNxWIz9JB12omIQdlKTFVEe9DuTNMmTzt6dTjYYmbH2ed+QxOTPmPy9O63rQn5o8k1m6pnnhc'
    'nyRkPUYj02i57ybpzt8br1jScWLNfLjhu/EGdYkckWK6p649zSO/5RVb69bv8x2Vqcp9Pe7FZz'
    'S5wvHzSkqO6aqdNBy4YvTu/pqDBQ4EHB4gkKTM+yLVd+5rX+XnFWm8ZrohIGTh5WEHdpVIx1/G'
    'VqdKD7kfmSnaoyw0U+6rmTdfLwrlgYJDrNzGKN9V89Sb//2OyZqOe4G0uithPGZvH0K91iXroz'
    '0NC08Gp3iLcZiNO8Pckx7yTH3hMXEbAw0HmY0KWheTHhGJ/tyYODHtOXnogzNo1ZY01UgZxG67'
    'h1RwHVPClXunXq/hPxw0Ey9odJMozMMb4n3qedVwP6PUuZ9B992xJ1+Zo8JQvpib/V6ud501j6'
    'c02tJpNpGg5HuVq6vfRTtTUy6vH2aletFPkoSTNfCPU4HJg4M4Eq4sCkKgfLykQPiNOetNVTk2'
    'YIiVryb6sbxNByR62b94SaJoUa66mKk1wVmYGEMFM7YWSUeTEwk1yFsYLHkyjU8cCo/TAfsRYn'
    'wxfqEych6ecazBrsE+x2ymxK5zCWf0Z5PlnudPb3933NltooWb6s87i7ura+uXYL1uLGdhyZLF'
    'MpMhOm8LI/VXoCWwaEBxXpfZWkSg9Tg7M8IVv30zAP42FbZclOvq9TI1QQZnka9ov8UJhmlsHd'
    'MgMCpWPVWtlU3c2Wur+y2d1sC/Wsu/Wrje0t9Wyl11tZ3+qubaqNnlrdWH/Q3epurGP3UK2sf6'
    'I+6q4/aCuDIEELEJiS9TAxpACaANHaNOaQ+p3EmpNNzCDcCQdwKh4WemjUMNkzaQxf1MSk4zCj'
    'JGYwLhAqCsdhzkDPjnsEWNTrFSmBostY1WUDq4dErJ9za6JewuonTPXcmqivY9ViqnDrdn2hfk'
    'q+gXVTes2rcCDdgyIKN5WsylEyyrVtIc4TNyS+IevygujzroL7l2VFdpo9RbWcIU9we8wOKN1P'
    'ipztZ0m2LpxAQiSnhFHZ46MH91VgJlEyHZs4h0Y50wGtl+WCPFuiVEARslmiVEF5R74HO2uw6g'
    'q8Uig73uH+FVi9KL72eEtmvwmzG82vPK49mJYUKVynDjUDuDOUowEQoachyatFmsK6aEosKWMs'
    'ibHTKkM+o/mtuURkVYV5ZiWDu2UZss4wSvo6arGfzqj6aTarXqJ4oJyV3ytRqqBIeVFsguLJt+'
    'Dnj5G9NWUbGUo0pmI9KRPl6DNADzKTcZIhlMWic4mPeUfRus7R+vl3BQsBeshKl0/y03N+Xp/7'
    '6Tk/r8/99Jyf19nPTx3Fkzdxp9V8xEa451rpPR1G3DLIG2pz6BTsVBggT6g79Mg2dRd7o0QuWe'
    'TVF1j690sU0vcD+aMSpQqKktfEXysgVeRd29mb31TUykx6aqgxQAMsU7shck/xIXPy6cT4FB00'
    'D42egfat1aPtOMz5PBPUTD7kx0dtEcFXbg7hlKZJpEbJvuWd9WptxSruhU7xrKqM2u7SM8KyiE'
    'PpLEsGoSYOvq/dZQuMcRIU1Hjp6W6rvVCXqMJyImhRQDJnhpHUl5TuLRZCZu+EwyJlCNK1dfOC'
    '0rKs7jqkUVLvMtL6vCOkLSMNEu2EknyQq4NmyqrRiP2hr979dYH4vWtfS/RN+1R88Zm+9ZvP6c'
    '/tWx98/tvb7Tsf/O5tl+yKg9/yHH4VB79lwO9ciVIF5TU0un94juTJFVy61vzWQ7p5elGzwcZW'
    'wlETA5MN8PZQm5/3QEaBOAyDFqOgRflvPTN9mzGqF/UkMpio1ARPsM5zigWlNlEDPcEjEYWZre'
    '4b2SgpIjyh0I0wRDolJic/o+LfMzcFdyK9l4T4G0/VpIgHeTHLzcxvD7FZORQbjx0/K6+UKFVQ'
    '3pRK/JIpVWTtAe48ldWmj8mmlHWOibagmlfCCPnU6WA0neutcgYeoKFfEL+vzEkEh8eyJt9q/t'
    'O26f8U9bnUGYQ1WiBeGxsajBYGYSlVxpEcPNGDXTzNLSxXI1SKTcfHBuNY8D/Oheq5mQjr18vB'
    'QG4oHEepHqjn5NUj1Cqo1/DI/6kcT09uQ8C15h8qrpPTLG0bSWBo4s8UT9qKv1wyF1weG6n0+R'
    'IfKX789sMogqcCoxkFOKDe+4Xv+2/76ul8YLdcNNtNKRQam9jsY1OgX+jABEfeILWNMPfWllQ2'
    'xUv2ggLS3VF9DE+7bb7tbKPmk+tdw1noG2t4KVN0huyAazDC4GXLMMzsdYaHNSDjETfLdZqTpB'
    '28J0cCT0WxfSzwHkfzHArjMLUKKhXH1zVXLxUZoDouNb+qcfzs55iriTA+6A0HdaE2JhQ5HTnn'
    'gWMYnpm8bV1wdzNlYiqEwMLJZWaesyMVocYFlBAuTS5sYSKY5djj+ZxHyTYxv6SePiPYhFdTtL'
    '6x5ZQdmzPEyxQJtUbOEB3smNvdRh8Tr3dyPAgwaoQc9g0AMEBLoObvrOShOrffBPSRIUBVAKM+'
    'uDHH3uGm7eLNE10S83Dj0kURpgIpWXNQ6S4NbbdggYeZBcssNdoKJg6CxZkSxQOFHsMDShWUi7'
    'Ih/jLDUlU+x6WLzT9aLLGS/yPpv0USTcazyW2OKkjSEb0xU2ilezQrC9vF3CcMYm1e4MuST10T'
    '6ePKLqtBBHkzm8hsFwSUZmJn4BMMSn/WsGh4xYSUkjUDXfCtcEcFyczDe2poYngQRdO2s7Rvcj'
    'Ibfcv2b7ws1F3nw26c5VBZwl0VuHt+CHdV4O45cHe+RCGYXZBSfOYoNZkz7D6yHUx/V//aonzg'
    'd1YIOGV+v/y2zdTVYFJ+yCT6sMkPmVSDSTmZ1F/g/2d5/982GMl0')))
_INDEX = {
    f.name: {
      'descriptor': f,
      'services': {s.name: s for s in f.service},
    }
    for f in FILE_DESCRIPTOR_SET.file
}


SchemasServiceDescription = {
  'file_descriptor_set': FILE_DESCRIPTOR_SET,
  'file_descriptor': _INDEX[u'go.chromium.org/luci/resultdb/proto/v1/schema.proto']['descriptor'],
  'service_descriptor': _INDEX[u'go.chromium.org/luci/resultdb/proto/v1/schema.proto']['services'][u'Schemas'],
}
