# Copyright 2024 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from recipe_engine import post_process

from PB.recipes.infra import gcs_dep_autoroller as gcs_dep_autoroller_pb

DEPS = [
    'recipe_engine/buildbucket',
    'recipe_engine/context',
    'recipe_engine/file',
    'recipe_engine/json',
    'recipe_engine/path',
    'recipe_engine/raw_io',
    'recipe_engine/step',
    'recipe_engine/properties',
    'depot_tools/git',
    'depot_tools/git_cl',
    'depot_tools/depot_tools',
]

PROPERTIES = gcs_dep_autoroller_pb.Inputs

COMMIT_MESSAGE = """
Roll GCS deps

This is an automated CL generated by the GCS dep autoroller.
Packages {source_packages} from the {source_url} repo are being
rolled into the {destination_packages} in the {destination_url} repo.

If a certain package does not show up in the diffs that means the packages
are already up-to-date.

The build that created this CL was https://ci.chromium.orh/b/{build_id}
"""


def RunSteps(api, inputs):
  source_dir = api.path.cleanup_dir / 'source_repo'
  destination_dir = api.path.cleanup_dir / 'destination_repo'

  api.git.checkout(
      inputs.source_url,
      submodules=False,
      ref='refs/heads/main',
      depth=1,
      dir_path=source_dir)

  api.git.checkout(
      inputs.destination_url,
      submodules=False,
      ref='refs/heads/main',
      depth=1,
      dir_path=destination_dir)

  source_packages = inputs.source_packages.split(',')
  source_packages_command_input = []
  destination_packages = inputs.destination_packages.split(',')
  destination_packages_command_input = []
  assert len(source_packages) == len(destination_packages)
  for i in range(len(source_packages)):
    source_packages_command_input.append('--source-package')
    source_packages_command_input.append(source_packages[i])
    destination_packages_command_input.append('--destination-package')
    destination_packages_command_input.append(destination_packages[i])

  api.step('roll_downstream_gcs_deps_script', [
      api.depot_tools.roll_downstream_gcs_deps_path,
      '--source-deps',
      source_dir / '/DEPS',
      '--destination-deps',
      destination_dir / '/DEPS',
      *source_packages_command_input,
      *destination_packages_command_input,
  ])

  def step_test_data():
    destination_rel_path = api.path.relpath(destination_dir / '/DEPS',
                                            destination_dir)
    return api.raw_io.test_api.stream_output_text(
        f'diff --git a/{destination_rel_path}'
        f' b/{destination_rel_path}')

  with api.context(cwd=destination_dir):
    api.git.new_branch('autoroller-branch', name='new-branch')
    diff_step = api.git(
        'diff', stdout=api.raw_io.output_text(), step_test_data=step_test_data)
    diff_step.presentation.logs['stdout'] = diff_step.stdout
    if not diff_step.stdout:
      return

    commit_message = COMMIT_MESSAGE.format(
        source_url=inputs.source_url,
        destination_url=inputs.destination_url,
        source_packages=inputs.source_packages,
        destination_packages=inputs.destination_packages,
        build_id=api.buildbucket.build.id,
    )

    api.git('commit', '-a', '-m', 'Roll GCS dependencies')
    reviewers = inputs.reviewers.split(',')
    reviewers_command_input = []
    for r in reviewers:
      reviewers_command_input.append('-r')
      reviewers_command_input.append(r)
    upload_args = [
        '--cq-dry-run',
        '--bypass-hooks',
        '--enable-auto-submit',
        *reviewers_command_input,
        '--send-email',
    ]

    api.git_cl.upload(commit_message, upload_args, name='git cl upload')
    api.git_cl(
        'issue',
        ['--json', api.json.output()],
        name='git cl issue',
    )


def GenTests(api):
  yield api.test(
      'basic',
      api.properties(
          source_url='https://chromium.googlesource.com/chromium/src.git',
          destination_url='https://pdfium.googlesource.com/pdfium.git',
          source_packages='src/third_party/llvm-build/Release+Asserts',
          destination_packages='third_party/llvm-build/Release+Asserts',
          reviewers='deadbeefeater@google.com',
      ),
      api.post_process(post_process.MustRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )

  yield api.test(
      'no_change',
      api.properties(
          source_url='https://chromium.googlesource.com/chromium/src.git',
          destination_url='https://pdfium.googlesource.com/pdfium.git',
          source_packages='src/third_party/llvm-build/Release+Asserts',
          destination_packages='third_party/llvm-build/Release+Asserts',
          reviewers='deadbeefeater@google.com',
      ),
      api.override_step_data(
          'git diff',
          stdout=api.raw_io.output_text(''),
      ),
      api.post_process(post_process.DoesNotRun, 'git cl upload'),
      api.post_process(post_process.DropExpectation),
  )
